import {
    AMMO_12_GAUGE_BIRDSHOT,
    AMMO_12_GAUGE_BIRDSHOT_AMMO_BOX,
    AMMO_12_GAUGE_BUCKSHOT,
    AMMO_12_GAUGE_BUCKSHOT_AMMO_BOX,
    AMMO_12_GAUGE_SLUG,
    AMMO_12_GAUGE_SLUG_AMMO_BOX
} from "./ammo/cal-12";
import {
    AMMO_22_CALIBER,
    AMMO_22_CALIBER_AMMO_BOX,
    AMMO_22_CALIBER_TR,
    AMMO_22_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-22";
import {
    AMMO_308_CALIBER,
    AMMO_308_CALIBER_AMMO_BOX,
    AMMO_308_CALIBER_AP,
    AMMO_308_CALIBER_AP_AMMO_BOX,
    AMMO_308_CALIBER_TR,
    AMMO_308_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-308";
import {
    AMMO_338_CALIBER,
    AMMO_338_CALIBER_AMMO_BOX,
    AMMO_338_CALIBER_AP,
    AMMO_338_CALIBER_AP_AMMO_BOX,
    AMMO_338_CALIBER_TR,
    AMMO_338_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-338";
import {
    AMMO_357_CALIBER,
    AMMO_357_CALIBER_AMMO_BOX,
    AMMO_357_CALIBER_AP,
    AMMO_357_CALIBER_AP_AMMO_BOX,
    AMMO_357_CALIBER_TR,
    AMMO_357_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-357";
import {
    AMMO_30_06_CALIBER,
    AMMO_30_06_CALIBER_AMMO_BOX,
    AMMO_30_06_CALIBER_AP,
    AMMO_30_06_CALIBER_AP_AMMO_BOX,
    AMMO_30_06_CALIBER_TR,
    AMMO_30_06_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-30-06";
import {
    AMMO_38_CALIBER,
    AMMO_38_CALIBER_AMMO_BOX,
    AMMO_38_CALIBER_AP,
    AMMO_38_CALIBER_AP_AMMO_BOX,
    AMMO_38_CALIBER_TR,
    AMMO_38_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-38";
import {
    AMMO_45_CALIBER,
    AMMO_45_CALIBER_AMMO_BOX,
    AMMO_45_CALIBER_AP,
    AMMO_45_CALIBER_AP_AMMO_BOX,
    AMMO_45_CALIBER_TR,
    AMMO_45_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-45";
import {
    AMMO_44_CALIBER,
    AMMO_44_CALIBER_AMMO_BOX,
    AMMO_44_CALIBER_AP,
    AMMO_44_CALIBER_AP_AMMO_BOX,
    AMMO_44_CALIBER_TR,
    AMMO_44_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-44";
import {
    AMMO_50_AE_CALIBER,
    AMMO_50_AE_CALIBER_AMMO_BOX,
    AMMO_50_AE_CALIBER_AP, AMMO_50_AE_CALIBER_AP_AMMO_BOX,
    AMMO_50_AE_CALIBER_TR, AMMO_50_AE_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-50-ae";
import {
    AMMO_50_BMG_CALIBER,
    AMMO_50_BMG_CALIBER_AMMO_BOX,
    AMMO_50_BMG_CALIBER_AP, AMMO_50_BMG_CALIBER_AP_AMMO_BOX, AMMO_50_BMG_CALIBER_TR,
    AMMO_50_BMG_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-50-bmg";
import {
    AMMO_545_39_CALIBER,
    AMMO_545_39_CALIBER_AMMO_BOX,
    AMMO_545_39_CALIBER_AP, AMMO_545_39_CALIBER_AP_AMMO_BOX,
    AMMO_545_39_CALIBER_TR, AMMO_545_39_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-545-39";
import {
    AMMO_556_45_CALIBER,
    AMMO_556_45_CALIBER_AMMO_BOX,
    AMMO_556_45_CALIBER_AP, AMMO_556_45_CALIBER_AP_AMMO_BOX,
    AMMO_556_45_CALIBER_TR, AMMO_556_45_CALIBER_TR_AMMO_BOX
} from "./ammo/cal-556-45";

export const AMMO = new Set([
    AMMO_12_GAUGE_BIRDSHOT,
    AMMO_12_GAUGE_BIRDSHOT_AMMO_BOX,
    AMMO_12_GAUGE_BUCKSHOT,
    AMMO_12_GAUGE_BUCKSHOT_AMMO_BOX,
    AMMO_12_GAUGE_SLUG,
    AMMO_12_GAUGE_SLUG_AMMO_BOX,

    AMMO_22_CALIBER,
    AMMO_22_CALIBER_AMMO_BOX,
    AMMO_22_CALIBER_TR,
    AMMO_22_CALIBER_TR_AMMO_BOX,

    AMMO_30_06_CALIBER,
    AMMO_30_06_CALIBER_AMMO_BOX,
    AMMO_30_06_CALIBER_AP,
    AMMO_30_06_CALIBER_AP_AMMO_BOX,
    AMMO_30_06_CALIBER_TR,
    AMMO_30_06_CALIBER_TR_AMMO_BOX,

    AMMO_38_CALIBER,
    AMMO_38_CALIBER_AMMO_BOX,
    AMMO_38_CALIBER_AP,
    AMMO_38_CALIBER_AP_AMMO_BOX,
    AMMO_38_CALIBER_TR,
    AMMO_38_CALIBER_TR_AMMO_BOX,

    AMMO_44_CALIBER,
    AMMO_44_CALIBER_AMMO_BOX,
    AMMO_44_CALIBER_AP,
    AMMO_44_CALIBER_AP_AMMO_BOX,
    AMMO_44_CALIBER_TR,
    AMMO_44_CALIBER_TR_AMMO_BOX,

    AMMO_45_CALIBER,
    AMMO_45_CALIBER_AMMO_BOX,
    AMMO_45_CALIBER_AP,
    AMMO_45_CALIBER_AP_AMMO_BOX,
    AMMO_45_CALIBER_TR,
    AMMO_45_CALIBER_TR_AMMO_BOX,

    AMMO_308_CALIBER,
    AMMO_308_CALIBER_AMMO_BOX,
    AMMO_308_CALIBER_AP,
    AMMO_308_CALIBER_AP_AMMO_BOX,
    AMMO_308_CALIBER_TR,
    AMMO_308_CALIBER_TR_AMMO_BOX,

    AMMO_338_CALIBER,
    AMMO_338_CALIBER_AMMO_BOX,
    AMMO_338_CALIBER_AP,
    AMMO_338_CALIBER_AP_AMMO_BOX,
    AMMO_338_CALIBER_TR,
    AMMO_338_CALIBER_TR_AMMO_BOX,

    AMMO_357_CALIBER,
    AMMO_357_CALIBER_AMMO_BOX,
    AMMO_357_CALIBER_AP,
    AMMO_357_CALIBER_AP_AMMO_BOX,
    AMMO_357_CALIBER_TR,
    AMMO_357_CALIBER_TR_AMMO_BOX,

    AMMO_50_AE_CALIBER,
    AMMO_50_AE_CALIBER_AMMO_BOX,
    AMMO_50_AE_CALIBER_AP,
    AMMO_50_AE_CALIBER_AP_AMMO_BOX,
    AMMO_50_AE_CALIBER_TR,
    AMMO_50_AE_CALIBER_TR_AMMO_BOX,

    AMMO_50_BMG_CALIBER,
    AMMO_50_BMG_CALIBER_AMMO_BOX,
    AMMO_50_BMG_CALIBER_AP,
    AMMO_50_BMG_CALIBER_AP_AMMO_BOX,
    AMMO_50_BMG_CALIBER_TR,
    AMMO_50_BMG_CALIBER_TR_AMMO_BOX,

    AMMO_545_39_CALIBER,
    AMMO_545_39_CALIBER_AMMO_BOX,
    AMMO_545_39_CALIBER_AP,
    AMMO_545_39_CALIBER_AP_AMMO_BOX,
    AMMO_545_39_CALIBER_TR,
    AMMO_545_39_CALIBER_TR_AMMO_BOX,

    AMMO_556_45_CALIBER,
    AMMO_556_45_CALIBER_AMMO_BOX,
    AMMO_556_45_CALIBER_AP,
    AMMO_556_45_CALIBER_AP_AMMO_BOX,
    AMMO_556_45_CALIBER_TR,
    AMMO_556_45_CALIBER_TR_AMMO_BOX,
]);
