import type { NewCharacter } from '../../src/connections/database/schema/index.ts';

export const charactersSeedData: NewCharacter[] = [
    { id: 'Puppet', name: 'Puppet (all puppets)' },
    { id: 'Prisoner', name: 'Prisoner (players)' },
    { id: 'Razor', name: 'Razor' },
    { id: 'Sentry', name: 'Sentry' },
    { id: 'SentryOld', name: 'Sentry (old)' },
    { id: 'ArmedNPC', name: 'Armed NPC' },
    { id: 'BP_Zombie_Nuclear', name: 'Nuclear Puppet' },
    { id: 'BP_Zombie_Nuclear_Fat_Male', name: 'Nuclear Puppet — Fat (male)' },
    { id: 'BP_Zombie_Nuclear_Fat_Female', name: 'Nuclear Puppet — Fat (female)' },
    { id: 'BP_Zombie_Nuclear_Muscular_Male', name: 'Nuclear Puppet — Muscular (male)' },
    { id: 'BP_Zombie_Nuclear_Muscular_Female', name: 'Nuclear Puppet — Muscular (female)' },
    { id: 'BP_Zombie_Hospital_Normal', name: 'Hospital Puppet' },
    { id: 'BP_Zombie_Hospital_Fat', name: 'Hospital Puppet — Fat' },
    { id: 'BP_Zombie_Hospital_Female', name: 'Hospital Puppet — Female' },
    { id: 'BP_Zombie_Hospital_Muscle', name: 'Hospital Puppet — Muscular' },
    { id: 'BP_Bear', name: 'Bear' },
    { id: 'BP_Boar', name: 'Boar' },
    { id: 'BP_Boar_Mutant', name: 'Boar Mutant' },
    { id: 'BP_Wolf', name: 'Wolf' },
    { id: 'BP_Wolf_Mutant', name: 'Wolf Mutant' },
    { id: 'BP_Deer', name: 'Deer' },
    { id: 'BP_Deer_Mutant', name: 'Deer Mutant' },
    { id: 'BP_Goat', name: 'Goat' },
    { id: 'BP_Horse', name: 'Horse' },
    { id: 'BP_Chicken', name: 'Chicken' },
    { id: 'BP_Donkey', name: 'Donkey' },
    { id: 'BP_Rabbit', name: 'Rabbit' },
];
