import type { NewItem } from '../../src/connections/database/schema/index.ts';

export const itemsSeedData: NewItem[] = [
    { id: '12_Gauge_Birdshot', name: '12 Gauge Birdshot' },
    { id: '12_Gauge_Birdshot_Ammobox', name: '12 Gauge Birdshot Ammo Box' },
    { id: '12_Gauge_Buckshot', name: '12 Gauge Buckshot' },
    { id: '12_Gauge_Buckshot_Ammobox', name: '12 Gauge Buckshot Ammo Box' },
    { id: '12_Gauge_Slug', name: '12 Gauge Slug' },
    { id: '12_Gauge_Slug_Ammobox', name: '12 Gauge Slug Ammo Box' },
    { id: '1H_Beam_Dildo', name: 'Beam Dildo' },
    { id: '1H_Brass_Knuckles', name: 'Brass Knuckles' },
    { id: '1H_Bushman', name: 'Bushman' },
    { id: '1H_Cleaver', name: 'Cleaver' },
    { id: '1H_Crowbar', name: 'Crowbar' },
    { id: '1H_Dildo', name: 'Dildo' },
    { id: '1H_EMpossible_Knife', name: 'EMpossible Knife' },
    { id: '1H_Hatchet', name: 'Hatchet' },
    { id: '1H_Hunter', name: 'Hunter' },
    { id: '1H_KitchenKnife', name: 'Kitchen Knife' },
    { id: '1H_KitchenKnife_02', name: 'Kitchen Knife 02' },
    { id: '1H_KitchenKnife_03', name: 'Kitchen Knife 03' },
    { id: '1H_KitchenKnife_04', name: 'Kitchen Knife 04' },
    { id: '1H_Kunai', name: 'Kunai' },
    { id: '1H_Little_Spade', name: 'Little Spade' },
    { id: '1H_Medieval_Sword', name: 'Medieval Sword' },
    { id: '1H_Metal_Pipe', name: 'Metal Pipe' },
    { id: '1H_Metal_Sword', name: 'Metal Sword' },
    { id: '1H_MK5000_Black', name: 'MK5000 Black' },
    { id: '1H_MK5000_Metal', name: 'MK5000 Metal' },
    { id: '1H_N9_Black', name: 'N9 Black' },
    { id: '1H_N9_White', name: 'N9 White' },
    { id: '1H_Police_Baton', name: 'Police Baton' },
    { id: '1H_Scalpel', name: 'Scalpel' },
    { id: '1H_Scout_Black', name: 'Scout Black' },
    { id: '1H_Scout_White', name: 'Scout White' },
    { id: '1H_Shuriken', name: 'Shuriken' },
    { id: '1H_Small_Axe', name: 'Small Axe' },
    { id: '1H_Traynors_Axe', name: 'Traynors Axe' },
    { id: '1H_Wrench_Pipe', name: 'Wrench Pipe' },
    { id: '2H_Axe', name: 'Axe' },
    { id: '2H_Baseball_Bat', name: 'Baseball Bat' },
    { id: '2H_Baseball_Bat_Blaze', name: 'Baseball Bat Blaze' },
    { id: '2H_Industrial_Gardening_Hoe', name: 'Industrial Gardening Hoe' },
    { id: '2H_Katana', name: 'Katana' },
    { id: '2H_Katana1', name: 'Katana Gold' },
    { id: '2H_Metal_Axe', name: 'Metal Axe' },
    { id: '2H_Metal_Baseball_Bat', name: 'Metal Baseball Bat' },
    { id: '2H_Pickaxe', name: 'Pickaxe' },
    { id: '2H_Pitchfork', name: 'Pitchfork' },
    { id: '2H_Pitchfork_Bent', name: 'Pitchfork Bent' },
    { id: '2H_Shovel_01', name: 'Shovel' },
    { id: '2H_Shovel_02', name: 'Shovel' },
    { id: '2H_Stone_Axe', name: 'Stone Axe' },
    { id: '2H_Tang_Dao', name: 'Tang Dao' },
    { id: '2H_Tang_Dao_Black_Dragon', name: 'Tang Dao Black Dragon' },
    { id: '2H_Tang_Dao_Damascus', name: 'Tang Dao Damascus' },
    { id: 'Absinthe', name: 'Absinthe' },
    { id: 'ActivatedCharcoal_01', name: 'Activated Charcoal Small' },
    { id: 'ActivatedCharcoal_02', name: 'Activated Charcoal Medium' },
    { id: 'ActivatedCharcoal_03', name: 'Activated Charcoal Big' },
    { id: 'Aeroplane_Repair_Kit', name: 'Aeroplane Repair Kit' },
    { id: 'African_Biltong', name: 'African Biltong' },
    { id: 'Agaricus_Augustus', name: 'Agaricus Augustus' },
    { id: 'Agaricus_Campestris', name: 'Agaricus Campestris' },
    { id: 'Aloe_Vera', name: 'Aloe Vera' },
    { id: 'Amanita_Muscaria', name: 'Amanita Muscaria' },
    { id: 'Amanita_Pantherina', name: 'Amanita Pantherina' },
    { id: 'Amanita_Phalloides', name: 'Amanita Phalloides' },
    { id: 'Amanita_Virosa', name: 'Amanita Virosa' },
    { id: 'Ammo_Crossbow_Bolt_Carbon', name: 'Carbon Crossbow Bolt' },
    { id: 'Ammo_Crossbow_Bolt_Metal', name: 'Metal Crossbow Bolt' },
    { id: 'Ammo_Crossbow_Bolt_Wooden', name: 'Wooden Crossbow Bolt' },
    { id: 'Antibiotics_01', name: 'Antibiotics Small' },
    { id: 'Antibiotics_02', name: 'Antibiotics Medium' },
    { id: 'Antibiotics_03', name: 'Antibiotics Big' },
    { id: 'AntiburnGel', name: 'Antiburn Gel' },
    { id: 'Apple', name: 'Apple' },
    { id: 'Apple_2', name: 'Apple 2' },
    { id: 'Apple_Seed_Bag', name: 'Apple Seed Bag' },
    { id: 'Apple_Seeds', name: 'Apple Seeds' },
    { id: 'Armillaria_Mellea', name: 'Armillaria Mellea' },
    { id: 'Armor_Police_Vest_01', name: 'Armor Police Vest' },
    { id: 'Armor_Tactical_Vest_01_01', name: 'Armor Tactical Vest 01' },
    { id: 'Armor_Tactical_Vest_01_02', name: 'Armor Tactical Vest 02' },
    { id: 'Armor_Tactical_Vest_01_03', name: 'Armor Tactical Vest 03' },
    { id: 'Armor_Tactical_Vest_01_04', name: 'Armor Tactical Vest 04' },
    { id: 'Armor_Tactical_Vest_01_05', name: 'Armor Tactical Vest 05' },
    { id: 'Aspirin', name: 'Aspirin' },
    { id: 'BabyFood', name: 'Baby Food' },
    { id: 'Backpack_02_01', name: 'Backpack 02 01' },
    { id: 'Backpack_02_02', name: 'Backpack 02 02' },
    { id: 'Backpack_02_03', name: 'Backpack 02 03' },
    { id: 'Backpack_02_04', name: 'Backpack 02 04' },
    { id: 'Backpack_02_05', name: 'Backpack 02 05' },
    { id: 'Bag_of_Almonds', name: 'Bag of Almonds' },
    { id: 'BakedBeans', name: 'Baked Beans' },
    { id: 'BakingSoda', name: 'Baking Soda' },
    { id: 'Bamboo_Hat_01', name: 'Bamboo Hat 01' },
    { id: 'Bamboo_Hat_02', name: 'Bamboo Hat 02' },
    { id: 'Banana', name: 'Banana' },
    { id: 'Banjo', name: 'Banjo' },
    { id: 'Barbed_Wire', name: 'Barbed Wire' },
    { id: 'Barberry', name: 'Barberry' },
    { id: 'Baseball_Cap_01', name: 'Baseball Cap 01' },
    { id: 'Baseball_Cap_02', name: 'Baseball Cap 02' },
    { id: 'Baseball_Cap_03', name: 'Baseball Cap 03' },
    { id: 'Baseball_Cap_04', name: 'Baseball Cap 04' },
    { id: 'Baseball_Cap_05', name: 'Baseball Cap 05' },
    { id: 'Baseball_Cap_06', name: 'Baseball Cap 06' },
    { id: 'Baseball_Cap_07', name: 'Baseball Cap 07' },
    { id: 'Baseball_Cap_08', name: 'Baseball Cap 08' },
    { id: 'Baseball_Cap_09', name: 'Baseball Cap 09' },
    { id: 'Baseball_Cap_10', name: 'Baseball Cap 10' },
    { id: 'Baseball_Cap_11', name: 'Baseball Cap 11' },
    { id: 'Baseball_Cap_12', name: 'Baseball Cap 12' },
    { id: 'Baseball_Cap_13', name: 'Baseball Cap 13' },
    { id: 'BaseExpansionKit_Lvl1', name: 'Base Expansion Kit Lvl1' },
    { id: 'BaseExpansionKit_Lvl2', name: 'Base Expansion Kit Lvl2' },
    { id: 'Batteries', name: 'Batteries' },
    { id: 'BCULock_Item', name: 'BCU Lock' },
    { id: 'Bedroll', name: 'Bedroll' },
    { id: 'BeefRavioli', name: 'Beef Ravioli' },
    { id: 'BeefStew', name: 'Beef Stew' },
    { id: 'Beenie_01', name: 'Beanie 01' },
    { id: 'Beenie_02', name: 'Beanie 02' },
    { id: 'Beenie_03', name: 'Beanie 03' },
    { id: 'Beenie_04', name: 'Beanie 04' },
    { id: 'Beenie_05', name: 'Beanie 05' },
    { id: 'Beenie_06', name: 'Beanie 06' },
    { id: 'Beenie_07', name: 'Beanie 07' },
    { id: 'Beenie_08', name: 'Beanie 08' },
    { id: 'Beenie_09', name: 'Beanie 09' },
    { id: 'Beer', name: 'Beer' },
    { id: 'Beet', name: 'Beet' },
    { id: 'Beijing_Shoes_01', name: 'Beijing Shoes 01' },
    { id: 'Beijing_Shoes_02', name: 'Beijing Shoes 02' },
    { id: 'Beijing_Shoes_03', name: 'Beijing Shoes 03' },
    { id: 'Beijing_Shoes_04', name: 'Beijing Shoes 04' },
    { id: 'Bell_Pepper', name: 'Bell Pepper' },
    { id: 'Belt_Pistol_Holster', name: 'Belt Pistol Holster' },
    { id: 'Bicycle_Wheel_54_622_Item', name: 'Bicycle Wheel 54 622' },
    { id: 'Bicycle_Wheel_60_622_Item', name: 'Bicycle Wheel 60 622' },
    { id: 'Big_Vehicle_StorageRack', name: 'Big Vehicle Storage Rack' },
    { id: 'Binoculars', name: 'Binoculars' },
    { id: 'Birthday_Cap_01', name: 'Birthday Cap' },
    { id: 'Blackberry', name: 'Blackberry' },
    { id: 'BlackOlives', name: 'Black Olives' },
    { id: 'BlackPepper', name: 'Black Pepper' },
    { id: 'Blueberries', name: 'Blueberries' },
    { id: 'Bobby_pin', name: 'Bobby Pin' },
    { id: 'Bobby_Pin_Pacage', name: 'Bobby Pin Package' },
    { id: 'Boletus_Edulis', name: 'Boletus Edulis' },
    { id: 'Bolts', name: 'Bolts' },
    { id: 'Bolts_Package_Box', name: 'Bolts Package Box' },
    { id: 'Bone', name: 'Bone' },
    { id: 'Book_Cooking_BBQ', name: 'Book Cooking BBQ' },
    { id: 'Book_Cooking_Cake', name: 'Book Cooking Cake' },
    { id: 'Book_Cooking_Casseroles', name: 'Book Cooking Casseroles' },
    { id: 'Book_Cooking_Drinks', name: 'Book Cooking Drinks' },
    { id: 'Book_Cooking_Pasta', name: 'Book Cooking Pasta' },
    { id: 'Book_Cooking_Pizza', name: 'Book Cooking Pizza' },
    { id: 'Book_Cooking_Rice', name: 'Book Cooking Rice' },
    { id: 'Book_Cooking_Soup', name: 'Book Cooking Soup' },
    { id: 'Book_Cooking_Stew', name: 'Book Cooking Stew' },
    { id: 'BoomBox_01', name: 'Boom Box 01' },
    { id: 'Boonie_Hat_01', name: 'Boonie Hat 01' },
    { id: 'Boonie_Hat_02', name: 'Boonie Hat 02' },
    { id: 'Boonie_Hat_03', name: 'Boonie Hat 03' },
    { id: 'Boonie_Hat_04', name: 'Boonie Hat 04' },
    { id: 'Boonie_Hat_05', name: 'Boonie Hat 05' },
    { id: 'Boonie_Hat_06', name: 'Boonie Hat 06' },
    { id: 'Boots_06_01', name: 'Boots 06 01' },
    { id: 'Boots_06_02', name: 'Boots 06 02' },
    { id: 'Boots_07_01', name: 'Boots 07 01' },
    { id: 'Boots_07_02', name: 'Boots 07 02' },
    { id: 'Boots_07_03', name: 'Boots 07 03' },
    { id: 'Bow_MicroStabilizer', name: 'Bow Micro Stabilizer' },
    { id: 'BowSilencer', name: 'Bow Silencer' },
    { id: 'BowSilencer_SlipOn', name: 'Bow Silencer Slip On' },
    { id: 'Boxer_Briefs_01', name: 'Boxer Briefs 01' },
    { id: 'Break_Oil', name: 'Break Oil' },
    { id: 'Breathing_Tube_01', name: 'Breathing Tube' },
    { id: 'Brick', name: 'Brick' },
    { id: 'Broccoli', name: 'Broccoli' },
    { id: 'Broccoli_Seed_Bag', name: 'Broccoli Seed Bag' },
    { id: 'Broccoli_Seeds', name: 'Broccoli Seeds' },
    { id: 'Bulletproof_Vest_01', name: 'Bulletproof Vest 01' },
    { id: 'Bulletproof_Vest_01_02', name: 'Bulletproof Vest 02' },
    { id: 'Bulletproof_Vest_01_03', name: 'Bulletproof Vest 03' },
    { id: 'Bulletproof_Vest_01_04', name: 'Bulletproof Vest 04' },
    { id: 'Bulletproof_Vest_01_05', name: 'Bulletproof Vest 05' },
    { id: 'Bundle_Of_Bobby_Pins', name: 'Bundle of Bobby Pins' },
    { id: 'Bundle_Of_Bricks', name: 'Bundle Of Bricks' },
    { id: 'Butter', name: 'Butter' },
    { id: 'C4', name: 'C4' },
    { id: 'C4_CircuitBoard', name: 'C4 Circuit Board' },
    { id: 'C4_Detonator', name: 'C4 Detonator' },
    { id: 'C4_Keypad', name: 'C4 Keypad' },
    { id: 'C4_Pack', name: 'C4 Pack' },
    { id: 'Cabbage', name: 'Cabbage' },
    { id: 'Cabbage_Seed_Bag', name: 'Cabbage Seed Bag' },
    { id: 'Cabbage_Seeds', name: 'Cabbage Seeds' },
    { id: 'Cal_22', name: '.22' },
    { id: 'Cal_22_Ammobox', name: '.22 Ammo Box' },
    { id: 'Cal_22_Ammobox_TR', name: '.22 TR Ammo Box' },
    { id: 'Cal_22_TR', name: '.22 TR' },
    { id: 'Cal_30-06', name: '.30-06' },
    { id: 'Cal_30-06_Ammobox', name: '.30-06 Ammo Box' },
    { id: 'Cal_30-06_Ammobox_AP', name: '.30-06 AP Ammo Box' },
    { id: 'Cal_30-06_Ammobox_TR', name: '.30-06 TR Ammo Box' },
    { id: 'Cal_30-06_AP', name: '.30-06 AP' },
    { id: 'Cal_30-06_TR', name: '.30-06 TR' },
    { id: 'Cal_308', name: '.308' },
    { id: 'Cal_308_Ammobox', name: '.308 Ammo Box' },
    { id: 'Cal_308_Ammobox_AP', name: '.308 AP Ammo Box' },
    { id: 'Cal_308_Ammobox_TR', name: '.308 TR Ammo Box' },
    { id: 'Cal_308_AP', name: '.308 AP' },
    { id: 'Cal_308_TR', name: '.308 TR' },
    { id: 'Cal_338', name: '.338' },
    { id: 'Cal_338_Ammobox', name: '.338 Ammo Box' },
    { id: 'Cal_338_Ammobox_AP', name: '.338 AP Ammo Box' },
    { id: 'Cal_338_Ammobox_TR', name: '.338 TR Ammo Box' },
    { id: 'Cal_338_AP', name: '.338 AP' },
    { id: 'Cal_338_TR', name: '.338 TR' },
    { id: 'Cal_357_Ammobox', name: '.357 Ammo Box' },
    { id: 'Cal_357_Ammobox_AP', name: '.357 AP Ammo Box' },
    { id: 'Cal_357_Ammobox_TR', name: '.357 TR Ammo Box' },
    { id: 'Cal_357_Viper', name: '.357' },
    { id: 'Cal_357_Viper_AP', name: '.357 AP' },
    { id: 'Cal_357_Viper_TR', name: '.357 TR' },
    { id: 'Cal_38', name: '.38' },
    { id: 'Cal_38_Ammobox', name: '.38 Ammo Box' },
    { id: 'Cal_38_Ammobox_AP', name: '.38 AP Ammo Box' },
    { id: 'Cal_38_Ammobox_TR', name: '.38 TR Ammo Box' },
    { id: 'Cal_38_AP', name: '.38 AP' },
    { id: 'Cal_38_TR', name: '.38 TR' },
    { id: 'Cal_40_PG-7M', name: 'PG-7M' },
    { id: 'Cal_40x46', name: '40x46 Grenade' },
    { id: 'Cal_44_Viper', name: '.44' },
    { id: 'Cal_44_Viper_Ammobox', name: '.44 Ammo Box' },
    { id: 'Cal_44_Viper_Ammobox_AP', name: '.44 AP Ammo Box' },
    { id: 'Cal_44_Viper_Ammobox_TR', name: '.44 TR Ammo Box' },
    { id: 'Cal_44_Viper_AP', name: '.44 AP' },
    { id: 'Cal_44_Viper_TR', name: '.44 TR' },
    { id: 'Cal_45', name: '.45' },
    { id: 'Cal_45_Ammobox', name: '.45 Ammo Box' },
    { id: 'Cal_45_Ammobox_TR', name: '.45 TR Ammo Box' },
    { id: 'Cal_45_AP', name: '.45 AP' },
    { id: 'Cal_45_AP_Ammobox', name: '.45 AP Ammo Box' },
    { id: 'Cal_45_TR', name: '.45 TR' },
    { id: 'Cal_5_45x39mm', name: '5.45x39mm' },
    { id: 'Cal_5_45x39mm_Ammobox', name: '5.45x39mm Ammo Box' },
    { id: 'Cal_5_45x39mm_Ammobox_TR', name: '5.45x39mm TR Ammo Box' },
    { id: 'Cal_5_45x39mm_AP', name: '5.45x39mm AP' },
    { id: 'Cal_5_45x39mm_AP_Ammobox', name: '5.45x39mm AP Ammo Box' },
    { id: 'Cal_5_45x39mm_TR', name: '5.45x39mm TR' },
    { id: 'Cal_5_56x45mm', name: '5.56x45mm' },
    { id: 'Cal_5_56x45mm_Ammobox', name: '5.56x45mm Ammo Box' },
    { id: 'Cal_5_56x45mm_Ammobox_TR', name: '5.56x45mm TR Ammo Box' },
    { id: 'Cal_5_56x45mm_AP', name: '5.56x45mm AP' },
    { id: 'Cal_5_56x45mm_AP_Ammobox', name: '5.56x45mm AP Ammo Box' },
    { id: 'Cal_5_56x45mm_TR', name: '5.56x45mm TR' },
    { id: 'Cal_50_AE', name: '.50 AE' },
    { id: 'Cal_50_AE_Ammobox', name: '.50 AE Ammo Box' },
    { id: 'Cal_50_AE_Ammobox_TR', name: '.50 AE TR Ammo Box' },
    { id: 'Cal_50_AE_AP', name: '.50 AE AP' },
    { id: 'Cal_50_AE_AP_Ammobox', name: '.50 AE AP Ammo Box' },
    { id: 'Cal_50_AE_TR', name: '.50 AE TR' },
    { id: 'Cal_50BMG', name: '.50 BMG' },
    { id: 'Cal_50BMG_Ammobox', name: '.50 BMG Ammo Box' },
    { id: 'Cal_50BMG_Ammobox_TR', name: '.50 BMG TR Ammo Box' },
    { id: 'Cal_50BMG_AP', name: '.50 BMG AP' },
    { id: 'Cal_50BMG_AP_Ammobox', name: '.50 BMG AP Ammo Box' },
    { id: 'Cal_50BMG_TR', name: '.50 BMG TR' },
    { id: 'Cal_7_62x39mm', name: '7.62x39mm' },
    { id: 'Cal_7_62x39mm_Ammobox', name: '7.62x39mm Ammo Box' },
    { id: 'Cal_7_62x39mm_Ammobox_TR', name: '7.62x39mm TR Ammo Box' },
    { id: 'Cal_7_62x39mm_AP', name: '7.62x39mm AP' },
    { id: 'Cal_7_62x39mm_AP_Ammobox', name: '7.62x39mm AP Ammo Box' },
    { id: 'Cal_7_62x39mm_TR', name: '7.62x39mm TR' },
    { id: 'Cal_7_62x54mmR', name: '7.62x54mmR' },
    { id: 'Cal_7_62x54mmR_Ammobox', name: '7.62x54mmR Ammo Box' },
    { id: 'Cal_7_62x54mmR_Ammobox_TR', name: '7.62x54mmR TR Ammo Box' },
    { id: 'Cal_7_62x54mmR_AP', name: '7.62x54mmR AP' },
    { id: 'Cal_7_62x54mmR_AP_Ammobox', name: '7.62x54mmR AP Ammo Box' },
    { id: 'Cal_7_62x54mmR_TR', name: '7.62x54mmR TR' },
    { id: 'Cal_7_92x57mm', name: '7.92x57mm' },
    { id: 'Cal_7_92x57mm_Ammobox', name: '7.92x57mm Ammo Box' },
    { id: 'Cal_7_92x57mm_Ammobox_TR', name: '7.92x57mm TR Ammo Box' },
    { id: 'Cal_7_92x57mm_AP', name: '7.92x57mm AP' },
    { id: 'Cal_7_92x57mm_AP_Ammobox', name: '7.92x57mm AP Ammo Box' },
    { id: 'Cal_7_92x57mm_TR', name: '7.92x57mm TR' },
    { id: 'Cal_9mm', name: '9x19mm' },
    { id: 'Cal_9mm_Ammobox', name: '9x19mm Ammo Box' },
    { id: 'Cal_9mm_Ammobox_TR', name: '9x19mm TR Ammo Box' },
    { id: 'Cal_9mm_AP', name: '9x19mm AP' },
    { id: 'Cal_9mm_AP_Ammobox', name: '9x19mm AP Ammo Box' },
    { id: 'Cal_9mm_TR', name: '9x19mm TR' },
    { id: 'Cal_9x39mm', name: '9x39mm' },
    { id: 'Cal_9x39mm_Ammobox', name: '9x39mm Ammo Box' },
    { id: 'Cal_9x39mm_Ammobox_TR', name: '9x39mm TR Ammo Box' },
    { id: 'Cal_9x39mm_AP', name: '9x39mm AP' },
    { id: 'Cal_9x39mm_AP_Ammobox', name: '9x39mm AP Ammo Box' },
    { id: 'Cal_9x39mm_TR', name: '9x39mm TR' },
    { id: 'Camera_Lens', name: 'Camera Lens' },
    { id: 'Camouflage_Jacket_01', name: 'Camouflage Jacket 01' },
    { id: 'Camouflage_Jacket_02', name: 'Camouflage Jacket 02' },
    { id: 'Camouflage_Jacket_03', name: 'Camouflage Jacket 03' },
    { id: 'Can01', name: 'Can 01' },
    { id: 'Can02', name: 'Can 02' },
    { id: 'Can03', name: 'Can 03' },
    { id: 'Can04', name: 'Can 04' },
    { id: 'Candle_01', name: 'Candle 01' },
    { id: 'Candy_Bob', name: 'Candy Bob' },
    { id: 'CandyCorn_01', name: 'CandyCorn' },
    { id: 'Cannabis_Bud', name: 'Cannabis Bud' },
    { id: 'Cannabis_Seed_Bag', name: 'Cannabis Seed Bag' },
    { id: 'Cannabis_Seeds', name: 'Cannabis Seeds' },
    { id: 'Canned_Corn', name: 'Canned Corn' },
    { id: 'Canned_Tuna', name: 'Canned Tuna' },
    { id: 'CannedCatFood', name: 'Canned Cat Food' },
    { id: 'CannedDogFood', name: 'Canned Dog Food' },
    { id: 'CannedFruitCoctail', name: 'Canned Fruit Cocktail' },
    { id: 'CannedGoulash', name: 'Canned Goulash' },
    { id: 'CannedPeach', name: 'Canned Peach' },
    { id: 'CannedPear', name: 'Canned Pear' },
    { id: 'CannedPeas', name: 'Canned Peas' },
    { id: 'CannedSardine', name: 'Canned Sardine' },
    { id: 'CannedSeafoodMix', name: 'Canned Seafood Mix' },
    { id: 'CannedSpaghetti', name: 'Canned Spaghetti' },
    { id: 'CanOpener', name: 'Can Opener' },
    { id: 'CantaloupeMelon', name: 'Cantaloupe Melon' },
    { id: 'Canteen', name: 'Canteen' },
    { id: 'Cantharellus_Cibarius', name: 'Cantharellus Cibarius' },
    { id: 'Car_Battery', name: 'Car Battery' },
    { id: 'Car_Battery_Cables', name: 'Car Battery Cables' },
    { id: 'Car_Jack', name: 'Car Jack' },
    { id: 'Car_Repair_Kit', name: 'Car Repair Kit' },
    { id: 'Carbon_Arrow', name: 'Carbon Arrow' },
    { id: 'Carbon_BroadHead_Arrow', name: 'Carbon Broadhead Arrow' },
    { id: 'Carrot', name: 'Carrot' },
    { id: 'Carrot_Seed_Bag', name: 'Carrot Seed Bag' },
    { id: 'Carrot_Seeds', name: 'Carrot Seeds' },
    { id: 'Cash', name: 'Cash' },
    { id: 'Cauliflower', name: 'Cauliflower' },
    { id: 'CD_Player', name: 'CD Player' },
    { id: 'Celery', name: 'Celery' },
    { id: 'CementBag', name: 'Cement Bag' },
    { id: 'Cereal_BunnyStars', name: 'Cereal Bunny Stars' },
    { id: 'Cereal_UpNGo', name: "Cereal Up'N'Go" },
    { id: 'Chainsaw', name: 'Chainsaw' },
    { id: 'Charcoal', name: 'Charcoal' },
    { id: 'Cheese', name: 'Cheese' },
    { id: 'CheesePacked', name: 'Cheese Packed' },
    { id: 'Cherry_Seed_Bag', name: 'Cherry Seed Bag' },
    { id: 'Cherry_Seeds', name: 'Cherry Seeds' },
    { id: 'Chilipeper', name: 'Chili Pepper' },
    { id: 'Chillipepper_Seed_Bag', name: 'Chilli pepper Seed Bag' },
    { id: 'ChilliPeppers_Seeds', name: 'Chilli Peppers Seeds' },
    { id: 'Chips', name: 'Chips' },
    { id: 'Chips2', name: 'Chips 2' },
    { id: 'Chips3', name: 'Chips 3' },
    { id: 'Chips4', name: 'Chips 4' },
    { id: 'ChocolateCandy_01', name: 'Chocolate Candy 01' },
    { id: 'ChocolateCandy_03', name: 'Chocolate Candy 03' },
    { id: 'ChocolateCandy_04', name: 'Chocolate Candy 04' },
    { id: 'ChocolateCandy_05', name: 'Chocolate Candy 05' },
    { id: 'ChocolateCandy_06', name: 'Chocolate Candy 06' },
    { id: 'ChocolateCandy_07', name: 'Chocolate Candy 07' },
    { id: 'ChocolateCandy_08', name: 'Chocolate Candy 08' },
    { id: 'ChocolateCandy_09', name: 'Chocolate Candy 09' },
    { id: 'ChocolateCandy_10', name: 'Chocolate Candy 10' },
    { id: 'ChocolateCandy_11', name: 'Chocolate Candy 11' },
    { id: 'Chow_Mein', name: 'Chow Mein' },
    { id: 'Christmas_Ball_01', name: 'Christmas Ball 01' },
    { id: 'Christmas_Ball_02', name: 'Christmas Ball 02' },
    { id: 'Christmas_Ball_03', name: 'Christmas Ball 03' },
    { id: 'Christmas_Ball_04', name: 'Christmas Ball 04' },
    { id: 'Christmas_Ball_05', name: 'Christmas Ball 05' },
    { id: 'Christmas_Ball_06', name: 'Christmas Ball 06' },
    { id: 'Christmas_Beanie_02', name: 'Christmas Beanie' },
    { id: 'Christmas_Box', name: 'Christmas Box' },
    { id: 'Christmas_Headband_01', name: 'Christmas Headband 01' },
    { id: 'Christmas_Pants_01', name: 'Christmas Pants 01' },
    { id: 'Christmas_Pants_02', name: 'Christmas Pants 02' },
    { id: 'Christmas_Slippers', name: 'Christmas Slippers' },
    { id: 'Christmas_Vest_01', name: 'Christmas Vest' },
    { id: 'Cigarettes', name: 'Classic Cigarettes Pack' },
    { id: 'Cigarettes1', name: 'Lucky Star Cigarettes Pack' },
    { id: 'Classic_Shirt_01', name: 'Classic Shirt 01' },
    { id: 'Classic_Shirt_02', name: 'Classic Shirt 02' },
    { id: 'Claymore', name: 'Claymore' },
    { id: 'Coal_01', name: 'Coal 01' },
    { id: 'CoalBag', name: 'Coal Bag' },
    { id: 'Cocoa_Powder', name: 'Cocoa Powder' },
    { id: 'Coconut', name: 'Coconut' },
    { id: 'Coffee', name: 'Coffee' },
    { id: 'Coffee_Cup', name: 'Coffee Cup' },
    { id: 'College_Jacket_01', name: 'College Jacket 01' },
    { id: 'College_Jacket_02', name: 'College Jacket 02' },
    { id: 'College_Jacket_03', name: 'College Jacket 03' },
    { id: 'College_Jacket_04', name: 'College Jacket 04' },
    { id: 'College_Jacket_05', name: 'College Jacket 05' },
    { id: 'College_Jacket_06', name: 'College Jacket 06' },
    { id: 'College_Jacket_07', name: 'College Jacket 07' },
    { id: 'College_Jacket_08', name: 'College Jacket 08' },
    { id: 'ColorCan_AmberYellow', name: 'Color Can Amber Yellow' },
    { id: 'ColorCan_BaronBrown', name: 'Color Can Baron Brown' },
    { id: 'ColorCan_Black', name: 'Color Can Black' },
    { id: 'ColorCan_CherryRed', name: 'Color Can Cherry Red' },
    { id: 'ColorCan_ColdCyan', name: 'Color Can Cold Cyan' },
    { id: 'ColorCan_ColdGrey', name: 'Color Can Cold Grey' },
    { id: 'ColorCan_CottonCandy', name: 'Color Can Cotton Candy' },
    { id: 'ColorCan_DarkBrown', name: 'Color Can Dark Brown' },
    { id: 'ColorCan_DarkGreen', name: 'Color Can Dark Green' },
    { id: 'ColorCan_DarkGrey', name: 'Color Can Dark Grey' },
    { id: 'ColorCan_DarkUrban', name: 'Color Can Dark Urban' },
    { id: 'ColorCan_DeepOrange', name: 'Color Can Deep Orange' },
    { id: 'ColorCan_EarthGreen', name: 'Color Can Earth Green' },
    { id: 'ColorCan_EarthGrey', name: 'Color Can Earth Grey' },
    { id: 'ColorCan_EarthRed', name: 'Color Can Earth Red' },
    { id: 'ColorCan_EarthYellow', name: 'Color Can Earth Yellow' },
    { id: 'ColorCan_FireEngineRed', name: 'Color Can Fire Engine Red' },
    { id: 'ColorCan_FlatBrown', name: 'Color Can Flat Brown' },
    { id: 'ColorCan_FlatGrey', name: 'Color Can Flat Grey' },
    { id: 'ColorCan_FlatWhite', name: 'Color Can Flat White' },
    { id: 'ColorCan_ForestGreen', name: 'Color Can Forest Green' },
    { id: 'ColorCan_GalaxyBlue', name: 'Color Can Galaxy Blue' },
    { id: 'ColorCan_GalaxyGrey', name: 'Color Can Galaxy Grey' },
    { id: 'ColorCan_HazyPurple', name: 'Color Can Hazy Purple' },
    { id: 'ColorCan_LightBrown', name: 'Color Can Light Brown' },
    { id: 'ColorCan_LightUrban', name: 'Color Can Light Urban' },
    { id: 'ColorCan_LimeGreen', name: 'Color Can Lime Green' },
    { id: 'ColorCan_NavyBlue', name: 'Color Can Navy Blue' },
    { id: 'ColorCan_NavyGrey', name: 'Color Can Navy Grey' },
    { id: 'ColorCan_PoliceBlue', name: 'Color Can Police Blue' },
    { id: 'ColorCan_RedChocolate', name: 'Color Can Red Chocolate' },
    { id: 'ColorCan_SnowWhite', name: 'Color Can Snow White' },
    { id: 'ColorCan_VelvetBrown', name: 'Color Can Velvet Brown' },
    { id: 'ColorCan_WarmGrey', name: 'Color Can Warm Grey' },
    { id: 'Combat_Helmet_01', name: 'Combat Helmet 01' },
    { id: 'Combat_Helmet_02', name: 'Combat Helmet 02' },
    { id: 'Combat_Helmet_03', name: 'Combat Helmet 03' },
    { id: 'Combat_Helmet_04', name: 'Combat Helmet 04' },
    { id: 'CombatBoots', name: 'Combat Boots' },
    { id: 'Compass', name: 'Compass' },
    { id: 'Compass_Advanced', name: 'Compass Advanced' },
    { id: 'Compass_Basic', name: 'Compass Basic' },
    { id: 'Compound_Bow', name: 'Compound Bow' },
    { id: 'Compound_Bow_Desert', name: 'Compound Bow Desert' },
    { id: 'Compound_Bow_Digital', name: 'Compound Bow Digital' },
    { id: 'Compound_Bow_Snow', name: 'Compound Bow Snow' },
    { id: 'Compound_Bow_US_Scorpion', name: 'Compound Bow US Scorpion' },
    { id: 'Compound_Bow_Woodland', name: 'Compound Bow Woodland' },
    { id: 'CompoundBowSight_3_Pin', name: 'Compound Bow Sight 3 Pin' },
    { id: 'CompoundBowSight_5_Pin', name: 'Compound Bow Sight 5 Pin' },
    { id: 'Construction_Earmuffs_01', name: 'Construction Earmuffs 01' },
    { id: 'Construction_Earmuffs_02', name: 'Construction Earmuffs 02' },
    { id: 'Construction_Earmuffs_03', name: 'Construction Earmuffs 03' },
    { id: 'Construction_Earmuffs_04', name: 'Construction Earmuffs 04' },
    { id: 'Construction_Gloves_01_01', name: 'Construction Gloves 01' },
    { id: 'Construction_Gloves_01_02', name: 'Construction Gloves 02' },
    { id: 'Construction_Gloves_01_03', name: 'Construction Gloves 03' },
    { id: 'Construction_Pants_01', name: 'Construction Pants 01' },
    { id: 'Construction_Pants_02', name: 'Construction Pants 02' },
    { id: 'Construction_Pants_03_Child1', name: 'Construction Pants 03' },
    { id: 'Coprinus_Comatus', name: 'Coprinus Comatus' },
    { id: 'Corn', name: 'Corn' },
    { id: 'Corn_flakes', name: 'Corn Flakes' },
    { id: 'Corn_Seed_Bag', name: 'Corn Seed Bag' },
    { id: 'Corn_Seeds', name: 'Corn Seeds' },
    { id: 'Crab_Apple', name: 'Crab Apple' },
    { id: 'Crackers', name: 'Crackers' },
    { id: 'Cream', name: 'Cream' },
    { id: 'Cricket', name: 'Cricket' },
    { id: 'Crutch', name: 'Crutch' },
    { id: 'Cuban_Cigar', name: 'Cuban Cigar' },
    { id: 'Cucumber', name: 'Cucumber' },
    { id: 'Cucumber_Seed_Bag', name: 'Cucumber Seed Bag' },
    { id: 'Cucumber_Seeds', name: 'Cucumber Seeds' },
    { id: 'Currant', name: 'Currant' },
    { id: 'Dandelion', name: 'Dandelion' },
    { id: 'Date', name: 'Date' },
    { id: 'Depleted_Uranium', name: 'Depleted Uranium' },
    { id: 'Depleted_Uranium_Container', name: 'Depleted Uranium Container' },
    { id: 'DialLock_Item', name: 'Dial Lock' },
    { id: 'Diary', name: 'Diary' },
    { id: 'Dirtbike_Wheel_110_80_R19_Item', name: 'Dirt bike Wheel 110 80 R19' },
    { id: 'Dirtbike_Wheel_90_90_R21_Item', name: 'Dirt bike Wheel 90 90 R21' },
    { id: 'Disposable_Mask', name: 'Disposable Mask' },
    { id: 'Diving_Mask', name: 'Diving Mask' },
    { id: 'Diving_Mask_With_Breathing_Tube', name: 'Diving Mask With Breathing Tube' },
    { id: 'Dog_Rose', name: 'Dog Rose' },
    { id: 'Double_Bang_Firecracker', name: 'Double Bang Firecracker' },
    { id: 'Drill', name: 'Drill' },
    { id: 'Driving_Gloves_01_01', name: 'Driving Gloves 01' },
    { id: 'Driving_Gloves_01_02', name: 'Driving Gloves 02' },
    { id: 'Driving_Gloves_01_03', name: 'Driving Gloves 03' },
    { id: 'Driving_Gloves_01_04', name: 'Driving Gloves 04' },
    { id: 'Duct_Tape', name: 'Duct Tape' },
    { id: 'DW715_Rail', name: 'DW715 Rail' },
    { id: 'Ear_Plugs', name: 'Ear Plugs' },
    { id: 'Earthworm', name: 'Earthworm' },
    { id: 'Egg', name: 'Egg' },
    { id: 'Electrical_Repair_Kit', name: 'Electrical Repair Kit' },
    { id: 'Electrician_Glove_01_01', name: 'Electrician Gloves 01' },
    { id: 'Electrician_Glove_01_02', name: 'Electrician Gloves 02' },
    { id: 'Electrician_Glove_01_03', name: 'Electrician Gloves 03' },
    { id: 'Electrician_Tools', name: 'Electrician Tools' },
    { id: 'ElectricityGenerator', name: 'Electricity Generator' },
    { id: 'ElectricityGenerator_Small', name: 'Electricity Generator Small' },
    { id: 'Emergency_bandage', name: 'Emergency bandage' },
    { id: 'Emergency_bandage_Big', name: 'Emergency bandage Big' },
    { id: 'EMP_Grenade', name: 'EMP Grenade' },
    { id: 'EmptyBag', name: 'Empty Bag' },
    { id: 'Energy_Drink_Red_Ghoul', name: 'Energy Drink Red Ghoul' },
    { id: 'Extreme_Helmet_01', name: 'Extreme Helmet' },
    { id: 'F_Undershirt_Bra_01', name: 'Female Undershirt Bra 01' },
    { id: 'F_Undershirt_Bra_02', name: 'Female Undershirt Bra 02' },
    { id: 'F_Undershirt_Bra_03', name: 'Female Undershirt Bra 03' },
    { id: 'F_Undershirt_Bra_04', name: 'Female Undershirt Bra 04' },
    { id: 'F_Undershirt_Bra_05', name: 'Female Undershirt Bra 05' },
    { id: 'Faceroll_Smasher', name: 'Faceroll Smasher' },
    { id: 'Feather', name: 'Feather' },
    { id: 'Fig', name: 'Fig' },
    { id: 'Fig_Seed_Bag', name: 'Fig Seed Bag' },
    { id: 'Fig_Seeds', name: 'Fig Seeds' },
    { id: 'Fireman_Helmet_01', name: 'Fireman Helmet' },
    { id: 'Fireworks_Big', name: 'Fireworks Big' },
    { id: 'Fireworks_Small', name: 'Fireworks Small' },
    { id: 'FishingFloater', name: 'Fishing Floater' },
    { id: 'FishingFloater1', name: 'Fishing Floater 1' },
    { id: 'FishingFloaterPack1', name: 'Fishing Floater Pack 1' },
    { id: 'FishingFloaterPack2', name: 'Fishing Floater Pack 2' },
    { id: 'FishingHook1', name: 'Fishing Hook 1' },
    { id: 'FishingHook2', name: 'Fishing Hook 2' },
    { id: 'FishingHook3', name: 'Fishing Hook 3' },
    { id: 'FishingHook4', name: 'Fishing Hook 4' },
    { id: 'FishingHookPack1', name: 'Fishing Hook Pack 1' },
    { id: 'FishingHookPack2', name: 'Fishing Hook Pack 2' },
    { id: 'FishingHookPack3', name: 'Fishing Hook Pack 3' },
    { id: 'FishingHookPack4', name: 'Fishing Hook Pack 4' },
    { id: 'FishingLine_1', name: 'Fishing Line 1' },
    { id: 'FishingLine_2', name: 'Fishing Line 2' },
    { id: 'FishingLine_3', name: 'Fishing Line 3' },
    { id: 'FishingLine_4', name: 'Fishing Line 4' },
    { id: 'FishingReel', name: 'Fishing Reel' },
    { id: 'FishingReelPro', name: 'Fishing Reel Pro' },
    { id: 'FishingRod', name: 'Fishing Rod' },
    { id: 'FishingRod_A', name: 'Fishing Rod A' },
    { id: 'FishingRod_B', name: 'Fishing Rod B' },
    { id: 'Fistula_Hepatica', name: 'Fistula Hepatica' },
    { id: 'FlareCartridge', name: 'Flare Cartridge' },
    { id: 'FlareItem', name: 'Flare Item' },
    { id: 'FlareItem_Blue', name: 'Flare Item Blue' },
    { id: 'FlareItem_Green', name: 'Flare Item Green' },
    { id: 'Flashbang', name: 'Flashbang' },
    { id: 'Flint_And_Steel', name: 'Flint And Steel' },
    { id: 'Frag_Grenade', name: 'Frag Grenade' },
    { id: 'Fungicide', name: 'Fungicide' },
    { id: 'Fuse_1000A', name: 'Fuse 1000A' },
    { id: 'Fuse_200A', name: 'Fuse 200A' },
    { id: 'Fuse_400A', name: 'Fuse 400A' },
    { id: 'Fuse_600A', name: 'Fuse 600A' },
    { id: 'Fuse_800A', name: 'Fuse 800A' },
    { id: 'Ganoderma_Lucidum', name: 'Ganoderma Lucidum' },
    { id: 'Garlic', name: 'Garlic' },
    { id: 'Garlic_Seed_Bag', name: 'Garlic Seed Bag' },
    { id: 'Garlic_Seeds', name: 'Garlic Seeds' },
    { id: 'Gas_Mask_01', name: 'Gas Mask 01' },
    { id: 'Gas_Mask_02', name: 'Gas Mask 02' },
    { id: 'Gas_Mask_03', name: 'Gas Mask 03' },
    { id: 'Gas_Mask_04', name: 'Gas Mask 04' },
    { id: 'GasLantern', name: 'Gas Lantern' },
    { id: 'Gasoline_Canister', name: 'Gasoline Canister' },
    { id: 'Gasoline_Canister_Small', name: 'Gasoline Canister Small' },
    { id: 'GasTank', name: 'Gas Tank' },
    { id: 'Geek_Goggels', name: 'Geek Goggles' },
    { id: 'Geiger_Counter_Analogue', name: 'Geiger Counter Analogue' },
    { id: 'Ghillie_Suit_Jacket_01', name: 'Ghillie Suit Jacket 01' },
    { id: 'Ghillie_Suit_Jacket_02', name: 'Ghillie Suit Jacket 02' },
    { id: 'Ghillie_Suit_Jacket_03', name: 'Ghillie Suit Jacket 03' },
    { id: 'Ghillie_Suit_Jacket_04', name: 'Ghillie Suit Jacket 04' },
    { id: 'Ghillie_Suit_Jacket_05', name: 'Ghillie Suit Jacket 05' },
    { id: 'Ghillie_Suit_Pants_01', name: 'Ghillie Suit Pants 01' },
    { id: 'Ghillie_Suit_Pants_02', name: 'Ghillie Suit Pants 02' },
    { id: 'Ghillie_Suit_Pants_03', name: 'Ghillie Suit Pants 03' },
    { id: 'Ghillie_Suit_Pants_04', name: 'Ghillie Suit Pants 04' },
    { id: 'Ghillie_Suit_Pants_05', name: 'Ghillie Suit Pants 05' },
    { id: 'Glass', name: 'Glass' },
    { id: 'GlassBottle01', name: 'Glass Bottle 01' },
    { id: 'GlassBottle02', name: 'Glass Bottle 02' },
    { id: 'GlassBottle03', name: 'Glass Bottle 03' },
    { id: 'GlassBottle04', name: 'Glass Bottle 04' },
    { id: 'Glue', name: 'Glue' },
    { id: 'GrapeFruit', name: 'Grapefruit' },
    { id: 'Grapes_Raw', name: 'Grapes Raw' },
    { id: 'Graphite', name: 'Graphite' },
    { id: 'Grasshopper', name: 'Grasshopper' },
    { id: 'GravelBag', name: 'Gravel Bag' },
    { id: 'GrillGrid', name: 'Grill Grid' },
    { id: 'Grinding_Stone_01', name: 'Grinding Stone 01' },
    { id: 'Grinding_Stone_02', name: 'Grinding Stone 02' },
    { id: 'GuavaHalves', name: 'Guava Halves' },
    { id: 'Guitar', name: 'Guitar' },
    { id: 'Gun_Powder', name: 'Gun Powder' },
    { id: 'Halloween_Anonymous_Mask_01', name: 'Halloween Anonymous Mask' },
    { id: 'Halloween_Mask_BabyDoll_02', name: 'Halloween Mask BabyDoll' },
    { id: 'Halloween_Mask_Clown_03', name: 'Halloween Mask Clown' },
    { id: 'Halloween_Mask_Greek', name: 'Halloween Mask Greek' },
    { id: 'Halloween_Mask_Hockey_04', name: 'Halloween Mask Hockey' },
    { id: 'Halloween_Mask_JohnDoe_05', name: 'Halloween Mask JohnDoe' },
    { id: 'Halloween_Mask_Knife', name: 'Halloween Mask Knife' },
    { id: 'Halloween_Mask_Lecter_06', name: 'Halloween Mask Lecter' },
    { id: 'Halloween_Mask_Plague_07', name: 'Halloween Mask Plague' },
    { id: 'Halloween_Mask_Scream', name: 'Halloween Mask Scream' },
    { id: 'Halloween_Mask_Smiley_08', name: 'Halloween Mask Smiley' },
    { id: 'Halloween_Mask_Wooden_09', name: 'Halloween Mask Wooden' },
    { id: 'Hand_Fan_01', name: 'Hand Fan 01' },
    { id: 'Harmonica', name: 'Harmonica' },
    { id: 'Hazelnuts', name: 'Hazelnuts' },
    { id: 'Hazmat_Suit_Modern', name: 'Hazmat Suit Modern' },
    { id: 'Hazmat_Suit_Vintage', name: 'Hazmat Suit Vintage' },
    { id: 'Head_Bags_01', name: 'Head Bags 01' },
    { id: 'Hemostatic_Dressing', name: 'Hemostatic Dressing' },
    { id: 'Herbicide', name: 'Herbicide' },
    { id: 'HH_Boots_01', name: 'HH Boots' },
    { id: 'HH_Shoes_01_01', name: 'HH Shoes 01 01' },
    { id: 'HH_Shoes_01_02', name: 'HH Shoes 01 02' },
    { id: 'HH_Shoes_01_03', name: 'HH Shoes 01 03' },
    { id: 'HH_Shoes_01_04', name: 'HH Shoes 01 04' },
    { id: 'HH_Shoes_02_01', name: 'HH Shoes 02 01' },
    { id: 'HH_Shoes_02_02', name: 'HH Shoes 02 02' },
    { id: 'HH_Shoes_02_03', name: 'HH Shoes 02 03' },
    { id: 'HH_Shoes_03_01', name: 'HH Shoes 03 01' },
    { id: 'HH_Shoes_03_02', name: 'HH Shoes 03 02' },
    { id: 'HH_Shoes_03_03', name: 'HH Shoes 03 03' },
    { id: 'HH_Shoes_03_04', name: 'HH Shoes 03 04' },
    { id: 'HH_Shoes_03_05', name: 'HH Shoes 03 05' },
    { id: 'HH_Shoes_03_06', name: 'HH Shoes 03 06' },
    { id: 'HH_Shoes_03_07', name: 'HH Shoes 03 07' },
    { id: 'HH_Shoes_04_01', name: 'HH Shoes 04 01' },
    { id: 'HH_Shoes_04_02', name: 'HH Shoes 04 02' },
    { id: 'HH_Shoes_04_03', name: 'HH Shoes 04 03' },
    { id: 'HH_Shoes_04_04', name: 'HH Shoes 04 04' },
    { id: 'HH_Shoes_05_01', name: 'HH Shoes 05 01' },
    { id: 'HH_Shoes_05_02', name: 'HH Shoes 05 02' },
    { id: 'HH_Shoes_05_03', name: 'HH Shoes 05 03' },
    { id: 'HighTop_Shoes', name: 'High Top Shoes' },
    { id: 'Hiking_Backpack_01_01', name: 'Hiking Backpack 01 01' },
    { id: 'Hiking_Backpack_01_02', name: 'Hiking Backpack 01 02' },
    { id: 'Hiking_Backpack_01_03', name: 'Hiking Backpack 01 03' },
    { id: 'Hiking_Backpack_01_04', name: 'Hiking Backpack 01 04' },
    { id: 'Hiking_Backpack_01_05', name: 'Hiking Backpack 01 05' },
    { id: 'Hiking_Backpack_Tyrone', name: 'Hiking Backpack Tyrone' },
    { id: 'Hiking_Boots_01', name: 'Hiking Boots 01' },
    { id: 'Hiking_Boots_02', name: 'Hiking Boots 02' },
    { id: 'Hiking_Boots_03', name: 'Hiking Boots 03' },
    { id: 'Hiking_Boots_04', name: 'Hiking Boots 04' },
    { id: 'Hip_Flask', name: 'Hip Flask' },
    { id: 'Hippie_Pants_01', name: 'Hippie Pants 01' },
    { id: 'Hippie_Pants_02', name: 'Hippie Pants 02' },
    { id: 'Hippie_Pants_03', name: 'Hippie Pants 03' },
    { id: 'Hippie_Pants_04', name: 'Hippie Pants 04' },
    { id: 'Hippie_Pants_05', name: 'Hippie Pants 05' },
    { id: 'Hippie_Pants_06', name: 'Hippie Pants 06' },
    { id: 'Hippie_Pants_07', name: 'Hippie Pants 07' },
    { id: 'Hippie_Pants_08', name: 'Hippie Pants 08' },
    { id: 'Hippie_Shirt_01', name: 'Hippie Shirt 01' },
    { id: 'Hippie_Shirt_02', name: 'Hippie Shirt 02' },
    { id: 'Hoodie_01', name: 'Hoodie 01' },
    { id: 'Hoodie_02', name: 'Hoodie 02' },
    { id: 'Hoodie_03', name: 'Hoodie 03' },
    { id: 'Hoodie_04', name: 'Hoodie 04' },
    { id: 'Hoodie_05', name: 'Hoodie 05' },
    { id: 'Hose', name: 'Hose' },
    { id: 'Hospital_Pants', name: 'Hospital Pants' },
    { id: 'Hospital_Shirt_01', name: 'Hospital Shirt' },
    { id: 'Icing_Sugar', name: 'Icing Sugar' },
    { id: 'Industrial_Fertilizer', name: 'Industrial Fertilizer' },
    { id: 'Inmate_Hoodie_01', name: 'Inmate Hoodie' },
    { id: 'Inmate_pants', name: 'Inmate Pants' },
    { id: 'Inmate_shirt_01', name: 'Inmate Shirt' },
    { id: 'Inonotus_Obliquus', name: 'Inonotus Obliquus' },
    { id: 'Instant_OatMeal', name: 'Instant Oat Meal' },
    { id: 'IntEA_Level1', name: 'Intelligence Enhancement Ampoule Level 1' },
    { id: 'IntEA_Level2', name: 'Intelligence Enhancement Ampoule Level 2' },
    { id: 'IntEA_Level3', name: 'Intelligence Enhancement Ampoule Level 3' },
    { id: 'Isopropyl_alcohol', name: 'Isopropyl alcohol' },
    { id: 'Jar', name: 'Jar' },
    { id: 'Jar_02', name: 'Jar 02' },
    { id: 'Jeans_01_01', name: 'Jeans 01 01' },
    { id: 'Jeans_01_02', name: 'Jeans 01 02' },
    { id: 'Jeans_01_03', name: 'Jeans 01 03' },
    { id: 'Jeans_01_04', name: 'Jeans 01 04' },
    { id: 'Jeans_02_01_V2', name: 'Jeans 02 01 V2' },
    { id: 'Jeans_02_02', name: 'Jeans 02 02' },
    { id: 'Jeans_02_03', name: 'Jeans 02 03' },
    { id: 'Jeans_02_04', name: 'Jeans 02 04' },
    { id: 'Jeans_02_05', name: 'Jeans 02 05' },
    { id: 'Jeans_02_06', name: 'Jeans 02 06' },
    { id: 'Jeans_02_07', name: 'Jeans 02 07' },
    { id: 'Jeans_02_08', name: 'Jeans 02 08' },
    { id: 'Jeans_02_09', name: 'Jeans 02 09' },
    { id: 'Jeans_Jersey_Jacket_01', name: 'Jeans Jersey Jacket 01' },
    { id: 'Jeans_Jersey_Jacket_02', name: 'Jeans Jersey Jacket 02' },
    { id: 'Jersey_01', name: 'Jersey 01' },
    { id: 'Jersey_02', name: 'Jersey 02' },
    { id: 'Jersey_03', name: 'Jersey 03' },
    { id: 'Jersey_04', name: 'Jersey 04' },
    { id: 'Jersey_05', name: 'Jersey 05' },
    { id: 'Jersey_06', name: 'Jersey 06' },
    { id: 'Jersey_07', name: 'Jersey 07' },
    { id: 'Jersey_08', name: 'Jersey 08' },
    { id: 'Jersey_09', name: 'Jersey 09' },
    { id: 'Jock_Jacket_01', name: 'Jock Jacket 01' },
    { id: 'Jock_Jacket_02', name: 'Jock Jacket 02' },
    { id: 'Jock_Jacket_03', name: 'Jock Jacket 03' },
    { id: 'Jock_Jacket_04', name: 'Jock Jacket 04' },
    { id: 'K6-3_Helmet', name: 'K6-3 Helmet' },
    { id: 'Kar98_Bayonet', name: 'Kar98 Bayonet' },
    { id: 'Ketchup', name: 'Ketchup' },
    { id: 'KeyCard', name: 'Key Card' },
    { id: 'KeyCardBunker_Level01', name: 'Key Card Bunker Level 01' },
    { id: 'KeyCardBunker_Level02', name: 'Key Card Bunker Level 02' },
    { id: 'Kicmovaca', name: 'Kicmovaca' },
    { id: 'Kilt_01', name: 'Kilt 01' },
    { id: 'Kilt_02', name: 'Kilt 02' },
    { id: 'Kilt_03', name: 'Kilt 03' },
    { id: 'Kilt_04', name: 'Kilt 04' },
    { id: 'Kilt_05', name: 'Kilt 05' },
    { id: 'Kilt_06', name: 'Kilt 06' },
    { id: 'Kilt_Brogue_Shoe_01', name: 'Kilt Brogue Shoe' },
    { id: 'Kilt_Sock_01', name: 'Kilt Sock 01' },
    { id: 'Kilt_Socks_02', name: 'Kilt Socks 02' },
    { id: 'Kilt_Socks_03', name: 'Kilt Socks 03' },
    { id: 'Kilt_Socks_04', name: 'Kilt Socks 04' },
    { id: 'Kilt_Socks_05', name: 'Kilt Socks 05' },
    { id: 'Kilt_Socks_06', name: 'Kilt Socks 06' },
    { id: 'Kitchen_Board_01', name: 'Kitchen Board 01' },
    { id: 'Kitchen_Board_02', name: 'Kitchen Board 02' },
    { id: 'Kiwi', name: 'Kiwi' },
    { id: 'Knife_Sheath', name: 'Knife Sheath' },
    { id: 'Laika_Body_Front', name: 'Laika Body Front' },
    { id: 'Laika_Body_Left', name: 'Laika Body Left' },
    { id: 'Laika_Body_Right', name: 'Laika Body Right' },
    { id: 'Laika_Body_Top', name: 'Laika Body Top' },
    { id: 'Laika_Bumper_Back_Item', name: 'Laika Bumper Back' },
    { id: 'Laika_Bumper_Front_Item', name: 'Laika Bumper Front' },
    { id: 'Laika_Door_Left_Item', name: 'Laika Door Left' },
    { id: 'Laika_Door_Right_Item', name: 'Laika Door Right' },
    { id: 'Laika_DoorHood_Item', name: 'Laika Door Hood' },
    { id: 'Laika_DoorTrunk_Item', name: 'Laika Door Trunk' },
    { id: 'Laika_Engine_Alternator_Item', name: 'Laika Engine Alternator' },
    { id: 'Laika_Lights_FrontLeft', name: 'Laika Lights Front Left' },
    { id: 'Laika_Lights_FrontRight', name: 'Laika Lights Front Right' },
    { id: 'Laika_Lights_RearLeft', name: 'Laika Lights Rear Left' },
    { id: 'Laika_Lights_RearRight', name: 'Laika Lights Rear Right' },
    { id: 'Laika_Seat_FrontLeft_Item', name: 'Laika Seat Front Left' },
    { id: 'Laika_Seat_FrontRight_Item', name: 'Laika Seat Front Right' },
    { id: 'Larve', name: 'Larve' },
    { id: 'Lead_Plate', name: 'Lead Plate' },
    { id: 'Leather_Backpack_01', name: 'Leather Backpack 01' },
    { id: 'Leather_Backpack_02', name: 'Leather Backpack 02' },
    { id: 'Leather_Backpack_03', name: 'Leather Backpack 03' },
    { id: 'Leather_Jacket', name: 'Leather Jacket' },
    { id: 'Leather_Shoes', name: 'Leather Shoes 01' },
    { id: 'Leather_Shoes_02', name: 'Leather Shoes 02' },
    { id: 'Lemon', name: 'Lemon' },
    { id: 'Lemon_Seed_Bag', name: 'Lemon Seed Bag' },
    { id: 'Lemon_Seeds', name: 'Lemon Seeds' },
    { id: 'Lepiota_Procera', name: 'Lepiota Procera' },
    { id: 'Lettuce', name: 'Lettuce' },
    { id: 'Lettuce_Seed_Bag', name: 'Lettuce Seed Bag' },
    { id: 'Lettuce_Seeds', name: 'Lettuce Seeds' },
    { id: 'Lighter', name: 'Lighter' },
    { id: 'Lime', name: 'Lime' },
    { id: 'Lock_Item_Advanced', name: 'Golden Lock' },
    { id: 'Lock_Item_Basic', name: 'Iron Lock' },
    { id: 'Lock_Items_Medium', name: 'Silver Lock' },
    { id: 'Lockpick_Advanced_Item', name: 'Lock Pick Advanced' },
    { id: 'Lockpick_Item', name: 'Lock Pick' },
    { id: 'Long_Paddle', name: 'Long Paddle' },
    { id: 'Long_wooden_stick', name: 'Long Wooden Stick' },
    { id: 'Lycoperdon_Gigantea', name: 'Lycoperdon Gigantea' },
    { id: 'M1_Bayonet', name: 'M1 Bayonet' },
    { id: 'M1_Clip', name: 'M1 Clip' },
    { id: 'M1_Medical_Helmet', name: 'M1 Medical Helmet' },
    { id: 'M1_Vietnam_Helmet', name: 'M1 Vietnam Helmet' },
    { id: 'M1911_Rail', name: 'M1911 Rail' },
    { id: 'M70_Bayonet', name: 'M70 Bayonet' },
    { id: 'MA1_Spitfire_01', name: 'MA1 Spitfire 01' },
    { id: 'MA1_Spitfire_02', name: 'MA1 Spitfire 02' },
    { id: 'MA1_Spitfire_03', name: 'MA1 Spitfire 03' },
    { id: 'MA1_Spitfire_04', name: 'MA1 Spitfire 04' },
    { id: 'Magazine_AK15', name: 'AK-15 Magazine' },
    { id: 'Magazine_AK47', name: 'AK-47 Magazine' },
    { id: 'Magazine_AKS_74U', name: 'AKS-74U Magazine' },
    { id: 'Magazine_AS_Val', name: 'AS Val Magazine' },
    { id: 'Magazine_AWM', name: 'AWM Magazine' },
    { id: 'Magazine_AWP', name: 'AWP Magazine' },
    { id: 'Magazine_Block21', name: 'Block21 Magazine' },
    { id: 'Magazine_CarbonHunter', name: 'Carbon Hunter Magazine' },
    { id: 'Magazine_DEagle_357', name: 'Desert Eagle .357 Magazine' },
    { id: 'Magazine_DEagle_50', name: 'Desert Eagle .50 Magazine ' },
    { id: 'Magazine_HS9', name: 'HS9 Magazine' },
    { id: 'Magazine_Hunter85_V2', name: 'Hunter85 Magazine' },
    { id: 'Magazine_Krueger', name: 'Krueger Magazine' },
    { id: 'Magazine_M16', name: 'M16 Magazine' },
    { id: 'Magazine_M1911', name: 'M1911 Magazine' },
    { id: 'Magazine_M249', name: 'M249 Magazine' },
    { id: 'Magazine_M82A1', name: 'M82A1 Magazine' },
    { id: 'Magazine_M9', name: 'M9 Magazine' },
    { id: 'Magazine_MP5', name: 'MP5 Magazine' },
    { id: 'Magazine_RPK', name: 'RPK Magazine' },
    { id: 'Magazine_SCAR_DMR', name: 'SCAR DMR Magazine' },
    { id: 'Magazine_SF19', name: 'SF19 Magazine' },
    { id: 'Magazine_SVD_Dragunov', name: 'SVD Dragunov Magazine' },
    { id: 'Magazine_UMP45', name: 'UMP45 Magazine' },
    { id: 'Magazine_VHS2', name: 'VHS2 Magazine' },
    { id: 'Magnifying_Glass', name: 'Magnifying Glass' },
    { id: 'Mango', name: 'Mango' },
    { id: 'Marine_Cap_01', name: 'Marine Cap 01' },
    { id: 'Marine_Cap_02', name: 'Marine Cap 02' },
    { id: 'Marine_Cap_03', name: 'Marine Cap 03' },
    { id: 'Marine_Cap_04', name: 'Marine Cap 04' },
    { id: 'Marine_Cap_05', name: 'Marine Cap 05' },
    { id: 'Marine_Cap_06', name: 'Marine Cap 06' },
    { id: 'Marine_Cap_07', name: 'Marine Cap 07' },
    { id: 'Matches', name: 'Matches' },
    { id: 'Mayonnaise', name: 'Mayonnaise' },
    { id: 'MeatSnack_01', name: 'Meat Snack 01' },
    { id: 'MeatSnack_02', name: 'Meat Snack 02' },
    { id: 'Medical_Glove_01', name: 'Medical Gloves' },
    { id: 'Medieval_Helmet_01', name: 'Medieval Helmet' },
    { id: 'MemoryModule_Level1', name: 'Memory Module Gray' },
    { id: 'MemoryModule_Level2', name: 'Memory Module Blue' },
    { id: 'MemoryModule_Level3', name: 'Memory Module Purple' },
    { id: 'MemoryModule_Level4', name: 'Memory Module Gold' },
    { id: 'Metal_Arrow', name: 'Metal Arrow' },
    { id: 'Metal_BroadHead_Arrow', name: 'Metal Broadhead Arrow' },
    { id: 'Metal_Scrap_01', name: 'Metal Scrap 01' },
    { id: 'Metal_Scrap_02', name: 'Metal Scrap 02' },
    { id: 'Metal_Scrap_03', name: 'Metal Scrap 03' },
    { id: 'Metal_Scrap_04', name: 'Metal Scrap 04' },
    { id: 'Metal_Scrap_05', name: 'Metal Scrap 05' },
    { id: 'MetalDetector', name: 'Metal Detector' },
    { id: 'Military_Backpack_01_01', name: 'Military Backpack 01 01' },
    { id: 'Military_Backpack_01_02', name: 'Military Backpack 01 02' },
    { id: 'Military_Backpack_01_03', name: 'Military Backpack 01 03' },
    { id: 'Military_Backpack_01_04', name: 'Military Backpack 01 04' },
    { id: 'Military_Backpack_01_05', name: 'Military Backpack 01 05' },
    { id: 'Military_Backpack_01_06', name: 'Military Backpack 01 06' },
    { id: 'Military_Backpack_01_07', name: 'Military Backpack 01 07' },
    { id: 'Military_Backpack_01_08', name: 'Military Backpack 01 08' },
    { id: 'Military_Backpack_02_01', name: 'Military Backpack 02 01' },
    { id: 'Military_Backpack_02_02', name: 'Military Backpack 02 02' },
    { id: 'Military_Backpack_02_03', name: 'Military Backpack 02 03' },
    { id: 'Military_Backpack_02_04', name: 'Military Backpack 02 04' },
    { id: 'Military_Backpack_02_05', name: 'Military Backpack 02 05' },
    { id: 'Military_Backpack_02_06', name: 'Military Backpack 02 06' },
    { id: 'Military_Backpack_02_07', name: 'Military Backpack 02 07' },
    { id: 'Military_Backpack_03_01', name: 'Military Backpack 03 01' },
    { id: 'Military_Backpack_03_02', name: 'Military Backpack 03 02' },
    { id: 'Military_Backpack_03_03', name: 'Military Backpack 03 03' },
    { id: 'Military_Backpack_03_04', name: 'Military Backpack 03 04' },
    { id: 'Military_Backpack_03_05', name: 'Military Backpack 03 05' },
    { id: 'Military_Backpack_03_06', name: 'Military Backpack 03 06' },
    { id: 'Military_Backpack_03_07', name: 'Military Backpack 03 07' },
    { id: 'Military_Backpack_03_08', name: 'Military Backpack 03 08' },
    { id: 'Military_Beanie_01', name: 'Military Beanie 01' },
    { id: 'Military_Beanie_02', name: 'Military Beanie 02' },
    { id: 'Military_Beanie_03', name: 'Military Beanie 03' },
    { id: 'Military_Beanie_04', name: 'Military Beanie 04' },
    { id: 'Military_Beanie_05', name: 'Military Beanie 05' },
    { id: 'Military_Beanie_06', name: 'Military Beanie 06' },
    { id: 'Military_Beanie_07', name: 'Military Beanie 07' },
    { id: 'Military_Beanie_08', name: 'Military Beanie 08' },
    { id: 'Military_Boonie_Hat_01', name: 'Military Boonie Hat 01' },
    { id: 'Military_Boonie_Hat_02', name: 'Military Boonie Hat 02' },
    { id: 'Military_Boonie_Hat_03', name: 'Military Boonie Hat 03' },
    { id: 'Military_Boonie_Hat_04', name: 'Military Boonie Hat 04' },
    { id: 'Military_Boonie_Hat_05', name: 'Military Boonie Hat 05' },
    { id: 'Military_Boonie_Hat_06', name: 'Military Boonie Hat 06' },
    { id: 'Military_Boonie_Hat_07', name: 'Military Boonie Hat 07' },
    { id: 'Military_Boonie_Hat_08', name: 'Military Boonie Hat 08' },
    { id: 'Military_Cap_01', name: 'Military Cap 01' },
    { id: 'Military_Cap_02', name: 'Military Cap 02' },
    { id: 'Military_Cap_03', name: 'Military Cap 03' },
    { id: 'Military_Cap_04', name: 'Military Cap 04' },
    { id: 'Military_Cap_05', name: 'Military Cap 05' },
    { id: 'Military_Cap_06', name: 'Military Cap 06' },
    { id: 'Military_Cap_07', name: 'Military Cap 07' },
    { id: 'Military_Cap_08', name: 'Military Cap 08' },
    { id: 'Military_Goggles_01', name: 'Military Goggles 01' },
    { id: 'Military_Helmet_01_01', name: 'Military Helmet 01' },
    { id: 'Military_Helmet_01_02', name: 'Military Helmet 02' },
    { id: 'Military_Helmet_01_03', name: 'Military Helmet 03' },
    { id: 'Military_Helmet_01_04', name: 'Military Helmet 04' },
    { id: 'Military_Helmet_01_05', name: 'Military Helmet 05' },
    { id: 'Military_Helmet_01_06', name: 'Military Helmet 06' },
    { id: 'Military_Helmet_01_07', name: 'Military Helmet 07' },
    { id: 'Military_Helmet_01_08', name: 'Military Helmet 08' },
    { id: 'Military_Helmet_01_09', name: 'Military Helmet 09' },
    { id: 'Military_Mask_01', name: 'Military Mask 01' },
    { id: 'Military_Mask_02', name: 'Military Mask 02' },
    { id: 'Military_Mask_03', name: 'Military Mask 03' },
    { id: 'Military_Mask_04', name: 'Military Mask 04' },
    { id: 'Military_Mask_05', name: 'Military Mask 05' },
    { id: 'Military_Mask_06', name: 'Military Mask 06' },
    { id: 'Military_Mask_07', name: 'Military Mask 07' },
    { id: 'Military_Mask_08', name: 'Military Mask 08' },
    { id: 'Military_Quiver_01', name: 'Military Quiver 01' },
    { id: 'Military_Quiver_02', name: 'Military Quiver 02' },
    { id: 'Military_Quiver_03', name: 'Military Quiver 03' },
    { id: 'Military_Quiver_04', name: 'Military Quiver 04' },
    { id: 'Military_Quiver_05', name: 'Military Quiver 05' },
    { id: 'Military_Quiver_06', name: 'Military Quiver 06' },
    { id: 'Military_Quiver_07', name: 'Military Quiver 07' },
    { id: 'Military_Shirt_01', name: 'Military Shirt 01' },
    { id: 'Military_Shirt_02', name: 'Military Shirt 02' },
    { id: 'Military_Shirt_03', name: 'Military Shirt 03' },
    { id: 'Military_Shirt_04', name: 'Military Shirt 04' },
    { id: 'Military_Shirt_05', name: 'Military Shirt 05' },
    { id: 'Military_Shirt_06', name: 'Military Shirt 06' },
    { id: 'Military_Shirt_07', name: 'Military Shirt 07' },
    { id: 'MilitaryBoots_JNA', name: 'Military Boots JNA' },
    { id: 'MilitaryBoots_Peace', name: 'Military Boots Peace' },
    { id: 'MilitaryPants_01', name: 'Military Pants 01' },
    { id: 'MilitaryPants_02', name: 'Military Pants 02' },
    { id: 'MilitaryPants_03', name: 'Military Pants 03' },
    { id: 'MilitaryPants_04', name: 'Military Pants 04' },
    { id: 'MilitaryPants_05', name: 'Military Pants 05' },
    { id: 'MilitaryPants_06', name: 'Military Pants 06' },
    { id: 'MilitaryPants_07', name: 'Military Pants 07' },
    { id: 'MilitaryPants_08', name: 'Military Pants 08' },
    { id: 'MilitaryPants_09', name: 'Military Pants 09' },
    { id: 'Milk', name: 'Milk' },
    { id: 'Mine_01', name: 'Mine 01' },
    { id: 'Mine_02', name: 'Mine 02' },
    { id: 'MMA_Glove_01', name: 'MMA Gloves' },
    { id: 'Mobile_Phone', name: 'Mobile Phone' },
    { id: 'Mosin_Bayonet', name: 'Mosin Bayonet' },
    { id: 'Motorcycle_Boots_01', name: 'Motorcycle Boots 01' },
    { id: 'Motorcycle_Boots_02', name: 'Motorcycle Boots 02' },
    { id: 'Motorcycle_Boots_03', name: 'Motorcycle Boots 03' },
    { id: 'Motorcycle_Glasses_01', name: 'Motorcycle Glasses 01' },
    { id: 'Motorcycle_Glasses_02', name: 'Motorcycle Glasses 02' },
    { id: 'Motorcycle_Jacket_01', name: 'Motorcycle Jacket 01' },
    { id: 'Motorcycle_Jacket_02', name: 'Motorcycle Jacket 02' },
    { id: 'Motorcycle_Jacket_03', name: 'Motorcycle Jacket 03' },
    { id: 'Motorcycle_Mask_01', name: 'Motorcycle Mask 01' },
    { id: 'Motorcycle_Mask_02', name: 'Motorcycle Mask 02' },
    { id: 'Motorcycle_Pants_01', name: 'Motorcycle Pants 01' },
    { id: 'Motorcycle_Pants_02', name: 'Motorcycle Pants 02' },
    { id: 'Motorcycle_Pants_03', name: 'Motorcycle Pants 03' },
    { id: 'MP5_Rail_Short', name: 'MP5 Rail Short' },
    { id: 'MRE_Cheeseburger', name: 'MRE Cheeseburger' },
    { id: 'MRE_Stew', name: 'MRE Stew' },
    { id: 'MRE_TunaSalad', name: 'MRE TunaSalad' },
    { id: 'Mulberry', name: 'Mulberry' },
    { id: 'Mustard', name: 'Mustard' },
    { id: 'Nails', name: 'Nails' },
    { id: 'Nails_Package_Box', name: 'Nails Package Box' },
    { id: 'Needle', name: 'Needle' },
    { id: 'Negan_Jacket', name: 'Negan Jacket' },
    { id: 'Night_Vision_Googles_01', name: 'Night Vision Goggles 01' },
    { id: 'Oak_Nuts', name: 'Oak Nuts' },
    { id: 'Oil_Filter', name: 'Oil Filter' },
    { id: 'Olives', name: 'Olives' },
    { id: 'Onion', name: 'Onion' },
    { id: 'Open_Finger_Gloves_01', name: 'Open Finger Gloves 01' },
    { id: 'Open_Finger_Gloves_02', name: 'Open Finger Gloves 02' },
    { id: 'Open_Finger_Gloves_03', name: 'Open Finger Gloves 03' },
    { id: 'Open_Finger_Gloves_04', name: 'Open Finger Gloves 04' },
    { id: 'Open_Finger_Gloves_05', name: 'Open Finger Gloves 05' },
    { id: 'Open_Finger_Gloves_06', name: 'Open Finger Gloves 06' },
    { id: 'Opuntia_Fig', name: 'Opuntia Fig' },
    { id: 'Orange', name: 'Orange' },
    { id: 'Organic_Fertilizer', name: 'Organic Fertilizer' },
    { id: 'Padlock', name: 'Padlock' },
    { id: 'Painkillers_01', name: 'Painkillers Small' },
    { id: 'Painkillers_02', name: 'Painkillers Medium' },
    { id: 'PainKillers_03', name: 'PainKillers Big' },
    { id: 'Pajama_Pants', name: 'Pajama Pants' },
    { id: 'Pajama_Shirt_01', name: 'Pajama Shirt' },
    { id: 'Pan', name: 'Pan' },
    { id: 'Pantyhose_01', name: 'Pantyhose 01' },
    { id: 'Paper', name: 'Paper' },
    { id: 'Parachute', name: 'Parachute' },
    { id: 'Parking_Sensor', name: 'Parking Sensor' },
    { id: 'Parsley', name: 'Parsley' },
    { id: 'Party_Glasses_01', name: 'Party Glasses 01' },
    { id: 'Party_Glasses_02', name: 'Party Glasses 02' },
    { id: 'Pasta', name: 'Pasta' },
    { id: 'Peach', name: 'Peach' },
    { id: 'Pear', name: 'Pear' },
    { id: 'Pear_Seed_Bag', name: 'Pear Seed Bag' },
    { id: 'Pear_Seeds', name: 'Pear Seeds' },
    { id: 'Pen', name: 'Pen' },
    { id: 'PenisWarmer_01', name: 'Penis Warmer 01' },
    { id: 'PenisWarmer_02', name: 'Penis Warmer 02' },
    { id: 'PenisWarmer_03', name: 'Penis Warmer 03' },
    { id: 'Peppers_Seed_Bag', name: 'Peppers Seed Bag' },
    { id: 'Peppers_Seeds', name: 'Peppers Seeds' },
    { id: 'Pesticide', name: 'Pesticide' },
    { id: 'PETBottle01', name: 'Caramel Soda' },
    { id: 'PETBottle02', name: 'Caramel Soda' },
    { id: 'PETBottle03', name: 'Lime Soda' },
    { id: 'PETBottle04', name: 'Lime Soda' },
    { id: 'Phoenix_Tears', name: 'Phoenix Tears' },
    { id: 'Phoenix_Tears_Small', name: 'Phoenix Tears Small' },
    { id: 'Pilot_Glasses', name: 'Pilot Glasses' },
    { id: 'Pilot_Hat_01', name: 'Pilot Hat' },
    { id: 'Pilot_Jacket', name: 'Pilot Jacket' },
    { id: 'Pine_Cone', name: 'Pine Cone' },
    { id: 'Pineapple', name: 'Pineapple' },
    { id: 'Pirate_EyePatch', name: 'Pirate Eye Patch' },
    { id: 'Pirate_Hat_01', name: 'Pirate Hat' },
    { id: 'Pirate_Hat_Sparrow_02', name: 'Pirate Hat Sparrow' },
    { id: 'Police_Backpack_01', name: 'Police Backpack 01' },
    { id: 'Police_Backpack_02', name: 'Police Backpack 02' },
    { id: 'Police_Backpack_03', name: 'Police Backpack 03' },
    { id: 'Police_Beanie_01', name: 'Police Beanie' },
    { id: 'Police_Boonie_Hat_01', name: 'Police Boonie Hat' },
    { id: 'Police_Bulletproof_Vest_01', name: 'Police Bulletproof Vest' },
    { id: 'Police_Cap_01', name: 'Police Cap 01' },
    { id: 'Police_Cap_02', name: 'Police Cap 02' },
    { id: 'Police_Gloves_01', name: 'Police Gloves' },
    { id: 'Police_Handgun_Holster', name: 'Police Handgun Holster' },
    { id: 'Police_Helmet_01', name: 'Police Helmet' },
    { id: 'Police_Jacket_01', name: 'Police Jacket' },
    { id: 'Police_Mask_01', name: 'Police Mask 01' },
    { id: 'Police_Open_Finger_Gloves_01', name: 'Police Open Finger Gloves' },
    { id: 'Police_Shirt_01', name: 'Police Shirt' },
    { id: 'pOLICE_Sweater_01', name: 'Police Sweater' },
    { id: 'Portable_Electric_Stove', name: 'Portable Electric Stove' },
    { id: 'Portable_Gas_Stove', name: 'Portable Gas Stove' },
    { id: 'PortableWorkLight', name: 'Portable Work Light' },
    { id: 'Pot1', name: 'Pot' },
    { id: 'PotassiumIodide_Pills_01', name: 'Potassium Iodide Pills Small' },
    { id: 'PotassiumIodide_Pills_02', name: 'Potassium Iodide Pills Medium' },
    { id: 'PotassiumIodide_Pills_03', name: 'Potassium Iodide Pills Big' },
    { id: 'Potato', name: 'Potato' },
    { id: 'Potato_Seed_Bag', name: 'Potato Seed Bag' },
    { id: 'Potatoes_Seeds', name: 'Potatoes Seeds' },
    { id: 'PremiumBoiliesPack', name: 'Premium Boilies Pack' },
    { id: 'Pressure_Dressing', name: 'Pressure Dressing' },
    { id: 'Prisoner_Head', name: 'Human Head' },
    { id: 'Prisoner_Head_No_teeth', name: 'Human Head (No Teeth)' },
    { id: 'Prisoner_Left_Arm', name: 'Human Left Arm' },
    { id: 'Prisoner_Left_Foot', name: 'Human Left Foot' },
    { id: 'Prisoner_Left_Leg', name: 'Human Left Leg' },
    { id: 'Prisoner_Right_Arm', name: 'Human Right Arm' },
    { id: 'Prisoner_Right_Foot', name: 'Human Right Foot' },
    { id: 'Prisoner_Right_Leg', name: 'Human Right Leg' },
    { id: 'Prisoner_Torso', name: 'Human Torso' },
    { id: 'PromTrap', name: 'Prom Trap' },
    { id: 'Psilocybe_Cyanescens', name: 'Psilocybe Cyanescens' },
    { id: 'Pumpkin', name: 'Pumpkin' },
    { id: 'Pumpkin_Seed_Bag', name: 'Pumpkin Seed Bag' },
    { id: 'Pumpkin_Seeds', name: 'Pumpkin Seeds' },
    { id: 'Puppet_Eye', name: 'Puppet Eye' },
    { id: 'Rabbit_Mask_01', name: 'Rabbit Mask' },
    { id: 'Racing_Helmet_01', name: 'Racing Helmet' },
    { id: 'Radio', name: 'Radio' },
    { id: 'Rag_Stripes', name: 'Rag Stripes' },
    { id: 'Rager_Body_Front', name: 'Rager Body Front' },
    { id: 'Rager_Body_Left', name: 'Rager Body Left' },
    { id: 'Rager_Body_Right', name: 'Rager Body Right' },
    { id: 'Rager_Body_Top', name: 'Rager Body Top' },
    { id: 'Rager_Bumper_Back_Item', name: 'Rager Bumper Back' },
    { id: 'Rager_Bumper_Front_Item', name: 'Rager Bumper Front' },
    { id: 'Rager_Door_BackLeft_Item', name: 'Rager Door Back Left' },
    { id: 'Rager_Door_BackRight_Item', name: 'Rager Door Back Right' },
    { id: 'Rager_Door_FrontLeft_Item', name: 'Rager Door Front Left' },
    { id: 'Rager_Door_FrontRight_Item', name: 'Rager Door Front Right' },
    { id: 'Rager_DoorHood_Item', name: 'Rager Door Hood' },
    { id: 'Rager_DoorTrunk_Item', name: 'Rager Door Trunk' },
    { id: 'Rager_Engine_Alternator_Item', name: 'Rager Engine Alternator' },
    { id: 'Rager_Lights_FrontLeft', name: 'Rager Lights Front Left' },
    { id: 'Rager_Lights_FrontRight', name: 'Rager Lights Front Right' },
    { id: 'Rager_Lights_RearLeft', name: 'Rager Lights Rear Left' },
    { id: 'Rager_Lights_RearRight', name: 'Rager Lights Rear Right' },
    { id: 'Rager_Seat_FrontLeft_Item', name: 'Rager Seat Front Left' },
    { id: 'Rager_Seat_FrontRight_Item', name: 'Rager Seat Front Right' },
    { id: 'Rags', name: 'Rags' },
    { id: 'Raincoat_01', name: 'Raincoat 01' },
    { id: 'Raincoat_02', name: 'Raincoat 02' },
    { id: 'Raincoat_03', name: 'Raincoat 03' },
    { id: 'Raincoat_04', name: 'Raincoat 04' },
    { id: 'Raincoat_05', name: 'Raincoat 05' },
    { id: 'Raincoat_06', name: 'Raincoat 06' },
    { id: 'Raisins', name: 'Raisins' },
    { id: 'Ramsons', name: 'Ramsons' },
    { id: 'Razor_Blade', name: 'Razor Blade' },
    { id: 'Rebar_Cutter', name: 'Rebar Cutter' },
    { id: 'Recurve_Bow', name: 'Recurve Bow' },
    { id: 'Recurve_Bow_100', name: 'Recurve Bow #100' },
    { id: 'Recurve_Bow_50', name: 'Recurve Bow #50' },
    { id: 'Recurve_Bow_60', name: 'Recurve Bow #60' },
    { id: 'Recurve_Bow_70', name: 'Recurve Bow #70' },
    { id: 'Recurve_Bow_80', name: 'Recurve Bow #80' },
    { id: 'Recurve_Bow_90', name: 'Recurve Bow #90' },
    { id: 'Redneck_Hat_07', name: 'Redneck Hat' },
    { id: 'RedOnion_Seed_Bag', name: 'Red Onion Seed Bag' },
    { id: 'RedOnion_Seeds', name: 'Red Onion Seeds' },
    { id: 'Refrigerator_Portable_Small', name: 'Refrigerator Portable Small' },
    { id: 'Respirator_01', name: 'Respirator 01' },
    { id: 'Retro_Helmet_01', name: 'Retro Helmet' },
    { id: 'RH_Arm_Guard', name: 'RH Arm Guard' },
    { id: 'RH_Bycoket_01', name: 'RH Bycoket 01' },
    { id: 'RH_Jacket', name: 'RH Jacket' },
    { id: 'RH_Shoe_01', name: 'RH Shoe' },
    { id: 'RH_Tights', name: 'RH Tights' },
    { id: 'Rice', name: 'Rice' },
    { id: 'Richards_Cheese', name: 'Richards Cheese' },
    { id: 'Rider_Helmet_01', name: 'Rider Helmet 01' },
    { id: 'Rider_Helmet_02', name: 'Rider Helmet 02' },
    { id: 'Rider_Helmet_03', name: 'Rider Helmet 03' },
    { id: 'Riot_Helmet_02', name: 'Riot Helmet' },
    { id: 'RK_Beanie_01', name: 'RK Beanie' },
    { id: 'RK_Hoodie_01', name: 'RayKit Hoodie' },
    { id: 'Rope1', name: 'Rope 1' },
    { id: 'Round_Sunglasses', name: 'Round Sunglasses' },
    { id: 'Rubber_band', name: 'Rubber Band' },
    { id: 'Rubber_sheet', name: 'Rubber Sheet' },
    { id: 'Safety_Goggles', name: 'Safety Goggles' },
    { id: 'Safety_pin', name: 'Safety Pin' },
    { id: 'SaltBag', name: 'Salt Bag' },
    { id: 'SaltGrain', name: 'Salt Grain' },
    { id: 'Santa_Hat_01', name: 'Santa Hat' },
    { id: 'Santa_Jacket', name: 'Santa Jacket' },
    { id: 'Santa_Pants', name: 'Santa Pants' },
    { id: 'Saw', name: 'Saw' },
    { id: 'School_Backpack_01', name: 'School Backpack 01' },
    { id: 'School_Backpack_Boy_02', name: 'School Backpack Boy 02' },
    { id: 'School_Backpack_Boy_03', name: 'School Backpack Boy 03' },
    { id: 'School_Backpack_Girl_04', name: 'School Backpack Girl 04' },
    { id: 'School_Backpack_Girl_05', name: 'School Backpack Girl 05' },
    { id: 'School_Backpack_Girl_06', name: 'School Backpack Girl 06' },
    { id: 'Scissors_01', name: 'Scissors 01' },
    { id: 'Scissors_Plastic', name: 'Scissors Plastic' },
    { id: 'ScopeRail_AK47', name: 'Scope Rail AK47' },
    { id: 'Scottish_Sporran_Bag_01', name: 'Scottish Sporran Bag 01' },
    { id: 'Screwdriver', name: 'Screwdriver Yellow' },
    { id: 'Screwdriver_Small', name: 'Screwdriver Red' },
    { id: 'Scum_Sunrise', name: 'Scum Sunrise' },
    { id: 'SCUMkin_Spice_Latte', name: 'SCUMkin Spice Latte' },
    { id: 'SeaSalt_01', name: 'Sea Salt 01' },
    { id: 'SeaSalt_02', name: 'Sea Salt 02' },
    { id: 'Sewing_kit', name: 'Sewing Kit' },
    { id: 'Sexy_Jeans_Shorts_01', name: 'Sexy Jeans Shorts 01' },
    { id: 'Sexy_Jeans_Shorts_02', name: 'Sexy Jeans Shorts 02' },
    { id: 'Sexy_Jeans_Shorts_03', name: 'Sexy Jeans Shorts 03' },
    { id: 'Sexy_Jeans_Shorts_04', name: 'Sexy Jeans Shorts 04' },
    { id: 'Sexy_Jeans_Shorts_05', name: 'Sexy Jeans Shorts 05' },
    { id: 'Sexy_Jeans_Shorts_06', name: 'Sexy Jeans Shorts 06' },
    { id: 'Sexy_Jeans_Shorts_07', name: 'Sexy Jeans Shorts 07' },
    { id: 'Shemagh_Scarf_01', name: 'Shemagh Scarf 01' },
    { id: 'Shemagh_Scarf_02', name: 'Shemagh Scarf 02' },
    { id: 'Shemagh_Scarf_03', name: 'Shemagh Scarf 03' },
    { id: 'Shemagh_Scarf_04', name: 'Shemagh Scarf 04' },
    { id: 'Shemagh_Scarf_05', name: 'Shemagh Scarf 05' },
    { id: 'Shemagh_Scarf_06', name: 'Shemagh Scarf 06' },
    { id: 'Shemagh_Scarf_07', name: 'Shemagh Scarf 07' },
    { id: 'Shemagh_Scarf_08', name: 'Shemagh Scarf 08' },
    { id: 'Shimoro_Pants', name: 'Shimoro Pants' },
    { id: 'Shimoro_Vest', name: 'Shimoro Vest' },
    { id: 'Shirt_01', name: 'Shirt 01' },
    { id: 'Shirt_02', name: 'Shirt 02' },
    { id: 'Shirt_03', name: 'Shirt 03' },
    { id: 'Short_Paddle_A', name: 'Short Paddle A' },
    { id: 'Short_Paddle_B', name: 'Short Paddle B' },
    { id: 'Short_Trousers_01_01', name: 'Short Trousers 01' },
    { id: 'Short_Trousers_01_02', name: 'Short Trousers 02' },
    { id: 'Short_Trousers_01_03', name: 'Short Trousers 03' },
    { id: 'Short_Trousers_01_04', name: 'Short Trousers 04' },
    { id: 'Short_Trousers_01_05', name: 'Short Trousers 05' },
    { id: 'Shorts_Pants_01_01', name: 'Shorts Pants 01 01' },
    { id: 'Shorts_Pants_01_02', name: 'Shorts Pants 01 02' },
    { id: 'Shorts_Pants_01_03', name: 'Shorts Pants 01 03' },
    { id: 'Shorts_Pants_01_04', name: 'Shorts Pants 01 04' },
    { id: 'Shorts_Pants_01_05', name: 'Shorts Pants 01 05' },
    { id: 'Shorts_Pants_01_06', name: 'Shorts Pants 01 06' },
    { id: 'Shorts_Pants_01_07', name: 'Shorts Pants 01 07' },
    { id: 'Shorts_Pants_01_08', name: 'Shorts Pants 01 08' },
    { id: 'Shorts_Pants_01_09', name: 'Shorts Pants 01 09' },
    { id: 'Shorts_Pants_01_10', name: 'Shorts Pants 01 10' },
    { id: 'Skirt_01_01', name: 'Skirt 01' },
    { id: 'Skirt_01_02', name: 'Skirt 02' },
    { id: 'Skirt_01_03', name: 'Skirt 03' },
    { id: 'Slav_Reviver', name: 'Slav Reviver' },
    { id: 'Slavic_Gent', name: 'Slavic Gent' },
    { id: 'Sledgehammer', name: 'Sledgehammer' },
    { id: 'Sleeveless_Camo_Shirt_01', name: 'Sleeveless Camo Shirt 01' },
    { id: 'Sleeveless_Camo_Shirt_02', name: 'Sleeveless Camo Shirt 02' },
    { id: 'Sleeveless_Camo_Shirt_03', name: 'Sleeveless Camo Shirt 03' },
    { id: 'Sleeveless_Camo_Shirt_04', name: 'Sleeveless Camo Shirt 04' },
    { id: 'Sleeveless_Camo_Shirt_05', name: 'Sleeveless Camo Shirt 05' },
    { id: 'Sleeveless_Shirt_01', name: 'Sleeveless Shirt 01' },
    { id: 'Sleeveless_Shirt_02', name: 'Sleeveless Shirt 02' },
    { id: 'Slippers_01', name: 'Slippers 01' },
    { id: 'Slippers_03', name: 'Slippers 03' },
    { id: 'Slouch_Camo_Hat_01', name: 'Slouch Camo Hat 01' },
    { id: 'Slouch_Camo_Hat_02', name: 'Slouch Camo Hat 02' },
    { id: 'Slouch_Camo_Hat_03', name: 'Slouch Camo Hat 03' },
    { id: 'Slouch_Camo_Hat_04', name: 'Slouch Camo Hat 04' },
    { id: 'Slouch_Camo_Hat_05', name: 'Slouch Camo Hat 05' },
    { id: 'Slouch_Hat_01', name: 'Slouch Hat 01' },
    { id: 'Slouch_Hat_02', name: 'Slouch Hat 02' },
    { id: 'Small_Oxygen_Bottle_01', name: 'Small Oxygen Bottle 01' },
    { id: 'Small_Vehicle_StorageRack', name: 'Small Vehicle Storage Rack' },
    { id: 'Smartphone_Battery', name: 'Smartphone Battery' },
    { id: 'Smoke_Grenade', name: 'Smoke Grenade' },
    { id: 'Smoke_Grenade_Green', name: 'Smoke Grenade Green' },
    { id: 'Smoke_Grenade_Red', name: 'Smoke Grenade Red' },
    { id: 'Smoke_Grenade_Violet', name: 'Smoke Grenade Violet' },
    { id: 'Smoke_Grenade_Yellow', name: 'Smoke Grenade Yellow' },
    { id: 'Sneakers_02_01', name: 'Sneakers 02 01' },
    { id: 'Sneakers_02_02', name: 'Sneakers 02 02' },
    { id: 'Sneakers_02_03', name: 'Sneakers 02 03' },
    { id: 'Sneakers_02_04', name: 'Sneakers 02 04' },
    { id: 'Snowballs_01', name: 'Snowballs 01' },
    { id: 'Snowballs_02', name: 'Snowballs 02' },
    { id: 'Soap', name: 'Soap' },
    { id: 'Sock_01', name: 'Sock 01' },
    { id: 'Socks_02', name: 'Socks 02' },
    { id: 'SoySauce', name: 'Soy Sauce' },
    { id: 'SpicesMix_01', name: 'Spices Mix 01' },
    { id: 'SpicesMix_02', name: 'Spices Mix 02' },
    { id: 'Spinach', name: 'Spinach' },
    { id: 'Spinach_Seed_Bag', name: 'Spinach Seed Bag' },
    { id: 'Spinach_Seeds', name: 'Spinach Seeds' },
    { id: 'Spon', name: 'Spon' },
    { id: 'Stabproof_Vest_01_01', name: 'Stab-proof Vest 01' },
    { id: 'Stabproof_Vest_01_02', name: 'Stab-proof Vest 02' },
    { id: 'Stabproof_Vest_01_03', name: 'Stab-proof Vest 03' },
    { id: 'Stabproof_Vest_01_04', name: 'Stab-proof Vest 04' },
    { id: 'Stabproof_Vest_01_05', name: 'Stab-proof Vest 05' },
    { id: 'Stabproof_Vest_01_06', name: 'Stab-proof Vest 06' },
    { id: 'Stabproof_Vest_01_07', name: 'Stab-proof Vest 07' },
    { id: 'Stabproof_Vest_01_08', name: 'Stab-proof Vest 08' },
    { id: 'Stabproof_Vest_01_09', name: 'Stab-proof Vest 09' },
    { id: 'Stone', name: 'Stone' },
    { id: 'Stone_Large', name: 'Stone Large' },
    { id: 'Stone_Small', name: 'Stone Small' },
    { id: 'Strait_Jacket', name: 'Strait Jacket' },
    { id: 'Sugar', name: 'Sugar' },
    { id: 'SugarBeet', name: 'Sugar Beet' },
    { id: 'Suite_Pants_01', name: 'Suite Pants 01' },
    { id: 'Super_Glue', name: 'Super Glue' },
    { id: 'Sweater_01', name: 'Sweater 01' },
    { id: 'Sweater_02', name: 'Sweater 02' },
    { id: 'Sweater_03', name: 'Sweater 03' },
    { id: 'Sweater_04', name: 'Sweater 04' },
    { id: 'Sweater_05', name: 'Sweater 05' },
    { id: 'SweetMelon_Seed_Bag', name: 'Sweet Melon Seed Bag' },
    { id: 'SweetMelons_Seeds', name: 'Sweet Melons Seeds' },
    { id: 'Syringe', name: 'Syringe' },
    { id: 'Tactical_Gloves_01_01', name: 'Tactical Gloves 01' },
    { id: 'Tactical_Gloves_01_02', name: 'Tactical Gloves 02' },
    { id: 'Tactical_Gloves_01_03', name: 'Tactical Gloves 03' },
    { id: 'Tactical_Gloves_01_04', name: 'Tactical Gloves 04' },
    { id: 'Tactical_Gloves_01_05', name: 'Tactical Gloves 05' },
    { id: 'Tactical_Gloves_01_06', name: 'Tactical Gloves 06' },
    { id: 'Tactical_Gloves_01_07', name: 'Tactical Gloves 07' },
    { id: 'Tactical_Gloves_01_08', name: 'Tactical Gloves 08' },
    { id: 'Tactical_Handgun_Holster_01', name: 'Tactical Handgun Holster 01' },
    { id: 'Tactical_Handgun_Holster_02', name: 'Tactical Handgun Holster 02' },
    { id: 'Tactical_Handgun_Holster_03', name: 'Tactical Handgun Holster 03' },
    { id: 'Tactical_Handgun_Holster_04', name: 'Tactical Handgun Holster 04' },
    { id: 'Tactical_Handgun_Holster_05', name: 'Tactical Handgun Holster 05' },
    { id: 'Tactical_Handgun_Holster_06', name: 'Tactical Handgun Holster 06' },
    { id: 'Tactical_Handgun_Holster_07', name: 'Tactical Handgun Holster 07' },
    { id: 'Tactical_Jacket_01_01', name: 'Tactical Jacket 01' },
    { id: 'Tactical_Jacket_01_02', name: 'Tactical Jacket 02' },
    { id: 'Tactical_Jacket_01_03', name: 'Tactical Jacket 03' },
    { id: 'Tactical_Jacket_01_04', name: 'Tactical Jacket 04' },
    { id: 'Tactical_Jacket_01_05', name: 'Tactical Jacket 05' },
    { id: 'Tactical_Jacket_01_06', name: 'Tactical Jacket 06' },
    { id: 'Tactical_Jacket_01_07', name: 'Tactical Jacket 07' },
    { id: 'Tactical_Jacket_01_09', name: 'Tactical Jacket 09' },
    { id: 'Tactical_Sunglasses_01', name: 'Tactical Sunglasses 01' },
    { id: 'Tactical_Sunglasses_02', name: 'Tactical Sunglasses 02' },
    { id: 'Tactical_Sweater_01', name: 'Tactical Sweater 01' },
    { id: 'Tactical_Sweater_02', name: 'Tactical Sweater 02' },
    { id: 'Tactical_Sweater_03', name: 'Tactical Sweater 03' },
    { id: 'Tactical_Sweater_04', name: 'Tactical Sweater 04' },
    { id: 'Tactical_Sweater_05', name: 'Tactical Sweater 05' },
    { id: 'Tactical_Sweater_06', name: 'Tactical Sweater 06' },
    { id: 'Tactical_Sweater_07', name: 'Tactical Sweater 07' },
    { id: 'Tactical_Vest_01', name: 'Tactical Vest' },
    { id: 'Tang_pants_01', name: 'Tang Pants 01' },
    { id: 'Tang_pants_02', name: 'Tang Pants 02' },
    { id: 'Tang_pants_03', name: 'Tang Pants 03' },
    { id: 'Tang_pants_04', name: 'Tang Pants 04' },
    { id: 'Tang_pants_05', name: 'Tang Pants 05' },
    { id: 'Tang_shirt_01', name: 'Tang Shirt 01' },
    { id: 'Tang_shirt_02', name: 'Tang Shirt 02' },
    { id: 'Tang_shirt_03', name: 'Tang Shirt 03' },
    { id: 'Tang_shirt_04', name: 'Tang Shirt 04' },
    { id: 'Tang_shirt_05', name: 'Tang Shirt 05' },
    { id: 'Tangerine', name: 'Tangerine' },
    { id: 'TC_Backpack', name: 'TC Backpack' },
    { id: 'Tea_Pack', name: 'Tea Pack' },
    { id: 'TearGasGrenade', name: 'Tear Gas Grenade' },
    { id: 'Tequila', name: 'Tequila' },
    { id: 'The_Island_Special', name: 'The Island Special' },
    { id: 'Thermometer', name: 'Thermometer' },
    { id: 'Thread', name: 'Thread' },
    { id: 'Tights_01_01', name: 'Tights 01 01' },
    { id: 'Tights_01_02', name: 'Tights 01 02' },
    { id: 'Tights_01_03', name: 'Tights 01 03' },
    { id: 'Tights_01_04', name: 'Tights 01 04' },
    { id: 'Tights_01_05', name: 'Tights 01 05' },
    { id: 'Tights_01_06', name: 'Tights 01 06' },
    { id: 'Tire_Repair_Kit', name: 'Tire Repair Kit' },
    { id: 'TNT', name: 'TNT' },
    { id: 'Toaster_Pastries', name: 'Toaster Pastries' },
    { id: 'Toaster_Pastries2', name: 'Toaster Pastries 2' },
    { id: 'Tobacco', name: 'Tobacco' },
    { id: 'Tobacco_Seed_Bag', name: 'Tobacco Seed Bag' },
    { id: 'Tobacco_Seeds', name: 'Tobacco Seeds' },
    { id: 'Tomato', name: 'Tomato' },
    { id: 'Tomato_Seed_Bag', name: 'Tomato Seed Bag' },
    { id: 'Tomatoes_Seeds', name: 'Tomatoes Seeds' },
    { id: 'TomatoPelate', name: 'Tomato Pelate' },
    { id: 'TomatoSouce', name: 'Tomato Sauce' },
    { id: 'Tool_Box', name: 'Tool Box' },
    { id: 'Tool_Box_Small', name: 'Tool Box Small' },
    { id: 'Tourniquet', name: 'Tourniquet' },
    { id: 'Tracksuit_Pants_01_01', name: 'Tracksuit Pants 01 01' },
    { id: 'Tracksuit_Pants_01_02', name: 'Tracksuit Pants 01 02' },
    { id: 'Tracksuit_Pants_01_03', name: 'Tracksuit Pants 01 03' },
    { id: 'Tracksuit_Pants_01_04', name: 'Tracksuit Pants 01 04' },
    { id: 'Tracksuit_Pants_01_05', name: 'Tracksuit Pants 01 05' },
    { id: 'Tracksuit_Pants_02_01', name: 'Tracksuit Pants 02 01' },
    { id: 'Tracksuit_Pants_02_02', name: 'Tracksuit Pants 02 02' },
    { id: 'Tracksuit_Pants_02_03', name: 'Tracksuit Pants 02 03' },
    { id: 'Tracksuit_Pants_02_04', name: 'Tracksuit Pants 02 04' },
    { id: 'Tracksuit_Pants_02_05', name: 'Tracksuit Pants 02 05' },
    { id: 'Tracksuit_Top_01', name: 'Tracksuit Top 01' },
    { id: 'Tracksuit_Top_02', name: 'Tracksuit Top 02' },
    { id: 'Tracksuit_Top_03', name: 'Tracksuit Top 03' },
    { id: 'Tracksuit_Top_04', name: 'Tracksuit Top 04' },
    { id: 'Tracksuit_Top_05', name: 'Tracksuit Top 05' },
    { id: 'Tree_Branches', name: 'Tree Branches' },
    { id: 'Trucker_Jacket_01', name: 'Trucker Jacket 01' },
    { id: 'Trucker_Jacket_02', name: 'Trucker Jacket 02' },
    { id: 'Trucker_Jacket_03', name: 'Trucker Jacket 03' },
    { id: 'Trucker_Jacket_04', name: 'Trucker Jacket 04' },
    { id: 'Tyrone_Shoelacez_Mask', name: 'Tyrone Shoelacez Mask' },
    { id: 'Underpants_01', name: 'Underpants 01' },
    { id: 'Underpants_02', name: 'Underpants 02' },
    { id: 'Underpants_03', name: 'Underpants 03' },
    { id: 'Underpants_04', name: 'Underpants 04' },
    { id: 'Underpants_05', name: 'Underpants 05' },
    { id: 'Undershirt_01', name: 'Undershirt' },
    { id: 'VegetableOil', name: 'Vegetable Oil' },
    { id: 'Vest_01', name: 'Vest 01' },
    { id: 'Vest_02', name: 'Vest 02' },
    { id: 'Vest_03', name: 'Vest 03' },
    { id: 'Vest_04', name: 'Vest 04' },
    { id: 'Vest_05', name: 'Vest 05' },
    { id: 'Vinegar', name: 'Vinegar' },
    { id: 'Vitamins_01', name: 'Vitamins Small' },
    { id: 'Vitamins_02', name: 'Vitamins Medium' },
    { id: 'Vitamins_03', name: 'Vitamins Big' },
    { id: 'Vodka', name: 'Vodka' },
    { id: 'Waist_Bag_Small_01', name: 'Waist Bag Small 01' },
    { id: 'Waist_Bag_Small_02', name: 'Waist Bag Small 02' },
    { id: 'Waist_Bag_Small_03', name: 'Waist Bag Small 03' },
    { id: 'Walnut', name: 'Walnut' },
    { id: 'Water_05l', name: 'Water 0.5l' },
    { id: 'Watering_Can', name: 'Watering Can' },
    { id: 'Watermelon', name: 'Watermelon' },
    { id: 'Watermelon_Seed_Bag', name: 'Watermelon Seed Bag' },
    { id: 'Watermelon_Seeds', name: 'Watermelon Seeds' },
    { id: 'Weapon_590A11', name: 'TEC01 490' },
    { id: 'Weapon_98k_Karabiner', name: 'Kar98k' },
    { id: 'Weapon_AK15', name: 'AK-15' },
    { id: 'Weapon_AK47', name: 'AK-47' },
    { id: 'Weapon_AK47_Engraved', name: 'AK-47 Engraved' },
    { id: 'Weapon_AKM', name: 'AKM' },
    { id: 'Weapon_AKS_74U', name: 'AKS-74U' },
    { id: 'Weapon_AS_Val', name: 'AS Val' },
    { id: 'Weapon_AT4_HEAT', name: 'AT4 HEAT' },
    { id: 'Weapon_AWM', name: 'AWM' },
    { id: 'Weapon_AWM_Desert', name: 'AWM Desert' },
    { id: 'Weapon_AWM_Green', name: 'AWM Green' },
    { id: 'Weapon_AWM_Snake', name: 'AWM Snake' },
    { id: 'Weapon_AWP', name: 'AWP' },
    { id: 'Weapon_AWP_Desert', name: 'AWP Desert' },
    { id: 'Weapon_AWP_Green', name: 'AWP Green' },
    { id: 'Weapon_AWP_Snake', name: 'AWP Snake' },
    { id: 'Weapon_BlackHawk_Crossbow', name: 'Black Hawk Crossbow' },
    { id: 'Weapon_Block21', name: 'Block 21' },
    { id: 'Weapon_CarbonHunter', name: 'Carbon Hunter' },
    { id: 'Weapon_Cleaning_Kit', name: 'Weapon Cleaning Kit' },
    { id: 'Weapon_Deagle_357', name: 'Desert Eagle .357' },
    { id: 'Weapon_Deagle_50', name: 'Desert Eagle .50' },
    { id: 'Weapon_DEagle_50Gold', name: 'Desert Eagle .50 Gold' },
    { id: 'Weapon_DT11B', name: 'DT11B' },
    { id: 'Weapon_DT11B_Sawed_Off', name: 'DT11B Sawed Off' },
    { id: 'Weapon_FlareGun', name: 'Flare Gun' },
    { id: 'Weapon_HS9', name: 'HS9' },
    { id: 'Weapon_Hunter85_V2', name: 'Hunter 85' },
    { id: 'Weapon_Judge44', name: 'Judge .44' },
    { id: 'Weapon_Krueger', name: 'Krueger' },
    { id: 'Weapon_M1_Garand', name: 'M1 Garand' },
    { id: 'Weapon_M16A4', name: 'M16A4' },
    { id: 'Weapon_M1887', name: 'M1887' },
    { id: 'Weapon_M1887_Sawed_off', name: 'M1887 Sawed Off' },
    { id: 'Weapon_M1911', name: 'M1911' },
    { id: 'Weapon_M1911_Engraved', name: 'M1911 Engraved' },
    { id: 'Weapon_M1911_Gold', name: 'M1911 Gold' },
    { id: 'Weapon_M1911_JayW', name: 'M1911 JayW' },
    { id: 'Weapon_M249', name: 'M249' },
    { id: 'Weapon_M82A1', name: 'M82A1' },
    { id: 'Weapon_M82A1_Black', name: 'M82A1 Black' },
    { id: 'Weapon_M82A1_Desert', name: 'M82A1 Desert' },
    { id: 'Weapon_M82A1_Snow', name: 'M82A1 Snow' },
    { id: 'Weapon_M9', name: 'M9' },
    { id: 'Weapon_M9_Silver', name: 'M9 Silver' },
    { id: 'Weapon_MK18', name: 'MK18' },
    { id: 'Weapon_MosinNagant', name: 'Mosin Nagant' },
    { id: 'Weapon_MP5', name: 'MP5' },
    { id: 'Weapon_MP5_K', name: 'MP5 K' },
    { id: 'Weapon_MP5_SD', name: 'MP5 SD' },
    { id: 'Weapon_PeaceKeeper38', name: 'Peace Keeper .38' },
    { id: 'Weapon_RPG7', name: 'RPG7' },
    { id: 'Weapon_RPK-74', name: 'RPK-74' },
    { id: 'Weapon_SCAR_DMR', name: 'SCAR DMR' },
    { id: 'Weapon_SDASS', name: 'SDASS' },
    { id: 'Weapon_Serpent357', name: 'Serpent .357' },
    { id: 'Weapon_SF19', name: 'SF19' },
    { id: 'Weapon_SVD_Dragunov', name: 'SVD Dragunov' },
    { id: 'Weapon_UMP45', name: 'UMP45' },
    { id: 'Weapon_VHS_BG', name: 'VHS BG' },
    { id: 'Weapon_VHS2', name: 'VHS2' },
    { id: 'Weapon_VHS2_Rail', name: 'VHS2 Rail' },
    { id: 'Weapon_Viper_M357', name: 'Viper M357' },
    { id: 'Weapon_VSS_VZ', name: 'VSS VZ' },
    { id: 'WeaponFlashHider', name: 'M1 Flash Hider' },
    { id: 'WeaponFlashlight_AS_Val', name: 'Weapon Flashlight AS Val' },
    { id: 'WeaponFlashlight_DesertEagle', name: 'Weapon Flashlight Desert Eagle' },
    { id: 'WeaponFlashlight_M9', name: 'Weapon Flashlight M9' },
    { id: 'WeaponGhillie_Desert', name: 'Weapon Ghillie Desert' },
    { id: 'WeaponGhillie_Winter', name: 'Weapon Ghillie Winter' },
    { id: 'WeaponGhillie_Woodland', name: 'Weapon Ghillie Woodland' },
    { id: 'WeaponScope_ACOG_01', name: 'ACOG Scope' },
    { id: 'WeaponScope_Dragunov', name: 'P-233 Scope' },
    { id: 'WeaponScope_HuntingScope', name: 'Hunting Scope' },
    { id: 'WeaponScope_M82A1', name: 'M82A1 Scope' },
    { id: 'WeaponScope_M82A1_Black', name: 'M82A1 Scope Black' },
    { id: 'WeaponScope_M82A1_Desert', name: 'M82A1 Scope Desert' },
    { id: 'WeaponScope_M82A1_Snow', name: 'M82A1 Scope Snow' },
    { id: 'WeaponScope_POSP', name: 'POSP Scope' },
    { id: 'WeaponScope_PU', name: 'PU Scope' },
    { id: 'WeaponScope_Vampyr', name: 'Vampyr Scope' },
    { id: 'WeaponScope_ZF39', name: 'ZF39 Scope' },
    { id: 'WeaponSights_AimPRO', name: 'Aim PRO Sight' },
    { id: 'WeaponSights_Deagle_RedDot', name: 'Desert Eagle Red Dot' },
    { id: 'WeaponSights_M1_Experimental', name: 'M1 Experimental Sight' },
    { id: 'WeaponSights_M1_ScopeAndSights', name: 'M1 Scope And Sights' },
    { id: 'WeaponSights_M16A4_FoldingSights', name: 'M16A4 Folding Sights' },
    { id: 'WeaponSights_MRO_Red_Dot', name: 'MRO Red Dot Sight' },
    { id: 'WeaponSights_OKP-7_Holographic', name: 'OKP-7 Holographic Sight' },
    { id: 'WeaponSights_RedDot_CA401B', name: 'Red Dot CA401B Sight' },
    { id: 'WeaponSights_Sentry_RDRS', name: 'Sentry RDRS Sight' },
    { id: 'WeaponSights_Shark', name: 'Shark Sight' },
    { id: 'WeaponSights_Snake', name: 'Snake Sight' },
    { id: 'WeaponSights_V3_Holographic', name: 'V3 Holographic Sight' },
    { id: 'WeaponSights_Wasp', name: 'Wasp Sight' },
    { id: 'WeaponSights_XPS300_Holographic', name: 'XPS300 Holographic Sight' },
    { id: 'WeaponSuppressor_12_Gauge', name: '12 Gauge Suppressor' },
    { id: 'WeaponSuppressor_30_06', name: '.30-06 Suppressor' },
    { id: 'WeaponSuppressor_308_Black', name: '.308 Suppressor Black' },
    { id: 'WeaponSuppressor_338_Black', name: '.338 Suppressor Black' },
    { id: 'WeaponSuppressor_338_Green', name: '.338 Suppressor Green' },
    { id: 'WeaponSuppressor_338_Tan', name: '.338 Suppressor Tan' },
    { id: 'WeaponSuppressor_45ACP', name: '.45ACP Suppressor' },
    { id: 'WeaponSuppressor_5_45x39', name: '5.45x39 Suppressor' },
    { id: 'WeaponSuppressor_AK15', name: 'AK15 Suppressor' },
    { id: 'WeaponSuppressor_Handgun', name: 'Handgun Suppressor' },
    { id: 'WeaponSuppressor_Hunter', name: 'Hunter Suppressor' },
    { id: 'WeaponSuppressor_Kar98k', name: 'Kar98k Suppressor' },
    { id: 'WeaponSuppressor_M1', name: 'M1 Suppressor' },
    { id: 'WeaponSuppressor_M1891', name: 'M1891 Suppressor' },
    { id: 'WeaponSuppressor_M82A1', name: 'M82A1 Suppressor' },
    { id: 'WeaponSuppressor_M82A1_Black', name: 'M82A1 Suppressor Black' },
    { id: 'WeaponSuppressor_M82A1_Desert', name: 'M82A1 Suppressor Desert' },
    { id: 'WeaponSuppressor_M82A1_Snow', name: 'M82A1 Suppressor Snow' },
    { id: 'WeaponSuppressor_MK18', name: 'MK18 Suppressor' },
    { id: 'WeaponSuppressor_MP5', name: 'MP5 Suppressor' },
    { id: 'WeaponSuppressor_SVD', name: 'SVD Suppressor' },
    { id: 'Wheel_155_R65_Item', name: 'Wheel 155 R65' },
    { id: 'Wheel_255_55_R16_Item', name: 'Wheel 255 55 R16' },
    { id: 'Wheel_265_60_R18_Item', name: 'Wheel 265 60 R18' },
    { id: 'Whiskey', name: 'Whiskey' },
    { id: 'WhiteFlour', name: 'White Flour' },
    { id: 'Wild_Cherry', name: 'Wild Cherry' },
    { id: 'Wild_Strawberry', name: 'Wild Strawberry' },
    { id: 'Wine', name: 'Wine' },
    { id: 'WineCork', name: 'Wine Cork' },
    { id: 'Wire', name: 'Wire' },
    { id: 'Wire_Cutters_01', name: 'Wire Cutters 01' },
    { id: 'Woodcuters_Shirt_01', name: 'Woodcutters Shirt 01' },
    { id: 'Woodcuters_Shirt_02', name: 'Woodcutters Shirt 02' },
    { id: 'Woodcuters_Shirt_03', name: 'Woodcutters Shirt 03' },
    { id: 'Wooden_Log_01', name: 'Wooden Log 01' },
    { id: 'Wooden_Log_02', name: 'Wooden Log 02' },
    { id: 'Wooden_Log_Small_01', name: 'Wooden Log Small 01' },
    { id: 'Wooden_Log_Small_02', name: 'Wooden Log Small 02' },
    { id: 'Wooden_Log_Small_03', name: 'Wooden Log Small 03' },
    { id: 'Wooden_Plank', name: 'Wooden Plank' },
    { id: 'Wool_Gloves_01_01', name: 'Wool Gloves 01' },
    { id: 'Wool_Gloves_01_02', name: 'Wool Gloves 02' },
    { id: 'Wool_Gloves_01_03', name: 'Wool Gloves 03' },
    { id: 'Wool_Gloves_01_04', name: 'Wool Gloves 04' },
    { id: 'Wool_Gloves_01_05', name: 'Wool Gloves 05' },
    { id: 'Wool_Gloves_01_06', name: 'Wool Gloves 06' },
    { id: 'Wool_Gloves_01_07', name: 'Wool Gloves 07' },
    { id: 'Work_Jacket_01', name: 'Work Jacket 01' },
    { id: 'Work_Jacket_02', name: 'Work Jacket 02' },
    { id: 'Work_Jacket_03', name: 'Work Jacket 03' },
    { id: 'Working_Helmet_01', name: 'Working Helmet 01' },
    { id: 'Working_Helmet_02', name: 'Working Helmet 02' },
    { id: 'Working_Helmet_03', name: 'Working Helmet 03' },
    { id: 'Working_Helmet_04', name: 'Working Helmet 04' },
    { id: 'Working_pants_01_01', name: 'Working Pants 01 01' },
    { id: 'Working_pants_01_02', name: 'Working Pants 01 02' },
    { id: 'Working_pants_01_03', name: 'Working Pants 01 03' },
    { id: 'Wushu_Spear_Metal', name: 'Wushu Spear Metal' },
    { id: 'Wushu_Spear_Wooden', name: 'Wushu Spear Wooden' },
    { id: 'WW_Body_Back', name: 'WW Body Back' },
    { id: 'WW_Body_Front', name: 'WW Body Front' },
    { id: 'WW_Body_Left', name: 'WW Body Left' },
    { id: 'WW_Body_Right', name: 'WW Body Right' },
    { id: 'WW_Body_Top', name: 'WW Body Top' },
    { id: 'WW_Bumper_Back_Item', name: 'WW Bumper Back' },
    { id: 'WW_Bumper_Front_Item', name: 'WW Bumper Front' },
    { id: 'WW_Door_BackLeft_Item', name: 'WW Door Back Left' },
    { id: 'WW_Door_BackRight_Item', name: 'WW Door Back Right' },
    { id: 'WW_Door_FrontLeft_Item', name: 'WW Door Front Left' },
    { id: 'WW_Door_FrontRight_Item', name: 'WW Door Front Right' },
    { id: 'WW_DoorHood_Item', name: 'WW Door Hood' },
    { id: 'WW_DoorTrunk_Item', name: 'WW Door Trunk' },
    { id: 'WW_Engine_Alternator_Item', name: 'WW Engine Alternator' },
    { id: 'WW_Lights_FrontLeft', name: 'WW Lights Front Left' },
    { id: 'WW_Lights_FrontRight', name: 'WW Lights Front Right' },
    { id: 'WW_Lights_RearLeft', name: 'WW Lights Rear Left' },
    { id: 'WW_Lights_RearRight', name: 'WW Lights Rear Right' },
    { id: 'WW_Seat_BackLeft_Item', name: 'WW Seat Back Left' },
    { id: 'WW_Seat_BackRight_Item', name: 'WW Seat Back Right' },
    { id: 'WW_Seat_FrontLeft_Item', name: 'WW Seat Front Left' },
    { id: 'WW_Seat_FrontRight_Item', name: 'WW Seat Front Right' },
    { id: 'WW2_German_Helmet_01', name: 'WW2 German Helmet 01' },
    { id: 'Yeast', name: 'Yeast' },
    { id: 'Zombie_01_Head', name: 'Puppet Head' },
    { id: 'Zombie_01_Head_No_teeth', name: 'Puppet Head (No Teeth)' },
    { id: 'Zombie_01_Left_Arm', name: 'Puppet Left Arm' },
    { id: 'Zombie_01_Left_Foot', name: 'Puppet Left Foot' },
    { id: 'Zombie_01_Left_Leg', name: 'Puppet Left Leg' },
    { id: 'Zombie_01_Right_Arm', name: 'Puppet Right Arm' },
    { id: 'Zombie_01_Right_Foot', name: 'Puppet Right Foot' },
    { id: 'Zombie_01_Right_Leg', name: 'Puppet Right Leg' },
    { id: 'Zombie_01_Torso', name: 'Puppet Torso' },
    { id: 'Zombie_Guts', name: 'Puppet Guts' },
    { id: 'Zombie_Impersonator_Suit', name: 'Zombie Impersonator Suit' },
    { id: 'Zucchini', name: 'Zucchini' },
    { id: 'Zucchini_Seed_Bag', name: 'Zucchini Seed Bag' },
    { id: 'Zucchini_Seeds', name: 'Zucchini Seeds' },
];
